import { PlayerClass, ElementType } from './types';

export type NodeType = 'root' | 'minor' | 'notable' | 'keystone';

export interface SkillTreeNode {
  id: string;
  name: string;
  type: NodeType;
  classType: PlayerClass | 'universal';
  icon: string;
  cost: number;
  x: number;
  y: number;
  connections: string[]; // IDs of connected neighbor nodes
  description: string;
  element?: ElementType;
  stats?: {
    maxHp?: number;
    defense?: number;
    moveSpeed?: number;
    pickupRadius?: number;
    damageBonus?: number;
    expMultiplier?: number;
  };
  signatureSkillId?: string; // Maps to signature ability in TRAIT_POOL
}

export interface ClassSkillTree {
  classType: PlayerClass | 'universal';
  title: string;
  elementTitle: string;
  rootId: string;
  nodes: Record<string, SkillTreeNode>;
}

export const CLASS_SKILL_TREES: Record<string, ClassSkillTree> = {
  [PlayerClass.SWORDSMAN]: {
    classType: PlayerClass.SWORDSMAN,
    title: 'The Steel Bulwark — 3 Archetype Mastery Web',
    elementTitle: '🩸 Rend & Crimson Steel',
    rootId: 'sw_root',
    nodes: {
      sw_root: {
        id: 'sw_root',
        name: 'Heart of Iron',
        type: 'root',
        classType: PlayerClass.SWORDSMAN,
        icon: '🛡️',
        cost: 0,
        x: 500,
        y: 350,
        connections: ['sw_atk_spd_1', 'sw_dmg_1', 'sw_def_1', 'sw_hp_1'],
        description: 'The ancestral core of the Steel Bulwark. Starting origin root.',
        stats: { maxHp: 10 }
      },

      // --- BUILD A: BLEED BERSERKER & WHIRLWIND (Top-Left) ---
      sw_atk_spd_1: {
        id: 'sw_atk_spd_1',
        name: 'Honed Edge',
        type: 'minor',
        classType: PlayerClass.SWORDSMAN,
        icon: '⚔️',
        cost: 95,
        x: 400,
        y: 260,
        connections: ['sw_root', 'sw_bleed_minor_1', 'sw_dmg_1'],
        description: '+8% All Damage and sword cleave radius.',
        stats: { damageBonus: 1 }
      },
      sw_bleed_minor_1: {
        id: 'sw_bleed_minor_1',
        name: 'Lacerating Fang',
        type: 'minor',
        classType: PlayerClass.SWORDSMAN,
        icon: '🩸',
        cost: 110,
        x: 320,
        y: 200,
        connections: ['sw_atk_spd_1', 'swordsman_whirlwind', 'sw_def_minor_1'],
        description: '+10 Max HP and attacks apply deep bleeding scratches.',
        stats: { maxHp: 10 }
      },
      swordsman_whirlwind: {
        id: 'swordsman_whirlwind',
        name: 'Blade Whirlwind',
        type: 'notable',
        classType: PlayerClass.SWORDSMAN,
        icon: '🌪️',
        cost: 360,
        x: 230,
        y: 150,
        connections: ['sw_bleed_minor_1', 'sw_rend_tear'],
        description: 'BUILD A NOTABLE: Periodic 360° cyclone slashing surrounding foes. Starts at Rank 1 (every 6th hit) and scales up to Rank 3 in match!',
        signatureSkillId: 'swordsman_whirlwind',
        element: ElementType.PHYSICAL_BLEED
      },
      sw_rend_tear: {
        id: 'sw_rend_tear',
        name: 'Rend & Tear',
        type: 'notable',
        classType: PlayerClass.SWORDSMAN,
        icon: '🩸',
        cost: 380,
        x: 160,
        y: 110,
        connections: ['swordsman_whirlwind', 'sw_keystone_bleed'],
        description: 'BUILD A NOTABLE: Slashes apply stacking lacerations (up to 5 stacks). Whirlwinds inflict bleed on all struck targets!',
        signatureSkillId: 'sw_rend_tear',
        element: ElementType.PHYSICAL_BLEED
      },
      sw_keystone_bleed: {
        id: 'sw_keystone_bleed',
        name: 'Crimson Cataclysm',
        type: 'keystone',
        classType: PlayerClass.SWORDSMAN,
        icon: '🩸',
        cost: 780,
        x: 90,
        y: 70,
        connections: ['sw_rend_tear'],
        description: 'BUILD A KEYSTONE: +30 Max HP. Whirlwinds consume bleed stacks to detonate a catastrophic blood explosion dealing 150% area damage!',
        stats: { maxHp: 30, damageBonus: 2 }
      },

      // --- BUILD B: SHOCKWAVE & SWORD SAINT (Top-Right) ---
      sw_dmg_1: {
        id: 'sw_dmg_1',
        name: 'Tempered Steel',
        type: 'minor',
        classType: PlayerClass.SWORDSMAN,
        icon: '🗡️',
        cost: 95,
        x: 600,
        y: 260,
        connections: ['sw_root', 'sw_atk_spd_1', 'sw_sonic_minor_1'],
        description: '+8% Damage and extended sword arc.',
        stats: { damageBonus: 1 }
      },
      sw_sonic_minor_1: {
        id: 'sw_sonic_minor_1',
        name: 'Vibrating Edge',
        type: 'minor',
        classType: PlayerClass.SWORDSMAN,
        icon: '⚡',
        cost: 110,
        x: 680,
        y: 200,
        connections: ['sw_dmg_1', 'swordsman_shockwave', 'sw_speed_1'],
        description: '+6% Movement Speed & razor edge velocity.',
        stats: { moveSpeed: 1 }
      },
      swordsman_shockwave: {
        id: 'swordsman_shockwave',
        name: 'Shockwave Slash',
        type: 'notable',
        classType: PlayerClass.SWORDSMAN,
        icon: '⚔️',
        cost: 380,
        x: 770,
        y: 150,
        connections: ['sw_sonic_minor_1', 'sw_blade_beam'],
        description: 'BUILD B NOTABLE: Slashes unleash piercing razor energy beams. Rank 1 has 35% proc chance, scaling to 100% at Rank 3!',
        signatureSkillId: 'swordsman_shockwave',
        element: ElementType.PHYSICAL_BLEED
      },
      sw_blade_beam: {
        id: 'sw_blade_beam',
        name: 'Blade Beam Volley',
        type: 'notable',
        classType: PlayerClass.SWORDSMAN,
        icon: '💥',
        cost: 400,
        x: 840,
        y: 110,
        connections: ['swordsman_shockwave', 'sw_keystone_shockwave'],
        description: 'BUILD B NOTABLE: Shockwaves split into twin crescent beams with 40% wider travel corridor and +20% damage.',
        signatureSkillId: 'sw_blade_beam',
        element: ElementType.PHYSICAL_BLEED
      },
      sw_keystone_shockwave: {
        id: 'sw_keystone_shockwave',
        name: 'Sundering Resonance',
        type: 'keystone',
        classType: PlayerClass.SWORDSMAN,
        icon: '⚡',
        cost: 800,
        x: 910,
        y: 70,
        connections: ['sw_blade_beam'],
        description: 'BUILD B KEYSTONE: Shockwaves leave vibrating rifts on the ground that implode after 1.0s pulling foes inward!',
        stats: { damageBonus: 2 }
      },

      // --- BUILD C: IRON FORTRESS & THORNS (Bottom-Left) ---
      sw_def_1: {
        id: 'sw_def_1',
        name: 'Carapace of Stone',
        type: 'minor',
        classType: PlayerClass.SWORDSMAN,
        icon: '🛡️',
        cost: 95,
        x: 400,
        y: 440,
        connections: ['sw_root', 'sw_def_minor_1', 'sw_hp_1'],
        description: '+2 Armor Defense, mitigating physical blows.',
        stats: { defense: 1 }
      },
      sw_def_minor_1: {
        id: 'sw_def_minor_1',
        name: 'Barbed Mail',
        type: 'minor',
        classType: PlayerClass.SWORDSMAN,
        icon: '🛡️',
        cost: 115,
        x: 320,
        y: 500,
        connections: ['sw_def_1', 'sw_bleed_minor_1', 'swordsman_retaliation'],
        description: '+2 Armor Defense & +10 Max HP.',
        stats: { defense: 1, maxHp: 10 }
      },
      swordsman_retaliation: {
        id: 'swordsman_retaliation',
        name: 'Iron Retaliation',
        type: 'notable',
        classType: PlayerClass.SWORDSMAN,
        icon: '🛡️',
        cost: 350,
        x: 230,
        y: 550,
        connections: ['sw_def_minor_1', 'sw_fortress_stance'],
        description: 'BUILD C NOTABLE: +Armor Defense and reflects damage taken as razor shrapnel. Scales across 3 ranks!',
        signatureSkillId: 'swordsman_retaliation',
        element: ElementType.PHYSICAL_BLEED
      },
      sw_fortress_stance: {
        id: 'sw_fortress_stance',
        name: 'Fortress Stance',
        type: 'notable',
        classType: PlayerClass.SWORDSMAN,
        icon: '🏰',
        cost: 390,
        x: 160,
        y: 590,
        connections: ['swordsman_retaliation', 'sw_keystone_juggernaut'],
        description: 'BUILD C NOTABLE: Taking hits builds Fortify stacks (+3 Armor each, max 5). At max stacks, releases a concussive stun slam!',
        signatureSkillId: 'sw_fortress_stance',
        element: ElementType.PHYSICAL_BLEED
      },
      sw_keystone_juggernaut: {
        id: 'sw_keystone_juggernaut',
        name: 'Immortal Bastion',
        type: 'keystone',
        classType: PlayerClass.SWORDSMAN,
        icon: '👑',
        cost: 820,
        x: 90,
        y: 630,
        connections: ['sw_fortress_stance'],
        description: 'BUILD C KEYSTONE: While below 40% HP, gain +12 Armor and regenerate 5% Max HP every 3.5 seconds. Become unbreakable.',
        stats: { defense: 2, maxHp: 35 }
      },

      // --- UTILITY & WARLORD HYBRID (Bottom-Right) ---
      sw_hp_1: {
        id: 'sw_hp_1',
        name: 'Vitality Tendril',
        type: 'minor',
        classType: PlayerClass.SWORDSMAN,
        icon: '❤️',
        cost: 95,
        x: 600,
        y: 440,
        connections: ['sw_root', 'sw_def_1', 'sw_speed_1'],
        description: '+15 Max HP permanently.',
        stats: { maxHp: 15 }
      },
      sw_speed_1: {
        id: 'sw_speed_1',
        name: 'Vanguard Stride',
        type: 'minor',
        classType: PlayerClass.SWORDSMAN,
        icon: '💨',
        cost: 100,
        x: 680,
        y: 500,
        connections: ['sw_hp_1', 'sw_sonic_minor_1', 'sw_magnet_1'],
        description: '+6% Movement Speed.',
        stats: { moveSpeed: 1 }
      },
      sw_magnet_1: {
        id: 'sw_magnet_1',
        name: 'Soul Magnet',
        type: 'minor',
        classType: PlayerClass.SWORDSMAN,
        icon: '🧲',
        cost: 110,
        x: 770,
        y: 550,
        connections: ['sw_speed_1', 'sw_blood_siphon'],
        description: '+25% EXP & Coin Magnet Radius.',
        stats: { pickupRadius: 1 }
      },
      sw_blood_siphon: {
        id: 'sw_blood_siphon',
        name: 'Bloodthirsty Siphon',
        type: 'notable',
        classType: PlayerClass.SWORDSMAN,
        icon: '🍷',
        cost: 370,
        x: 840,
        y: 590,
        connections: ['sw_magnet_1', 'sw_keystone_warlord'],
        description: 'WARLORD NOTABLE: Slaying bleeding or stunned foes restores +2 HP and grants +10% movement speed for 3s.',
        signatureSkillId: 'sw_blood_siphon',
        element: ElementType.PHYSICAL_BLEED
      },
      sw_keystone_warlord: {
        id: 'sw_keystone_warlord',
        name: 'Eternal Warlord',
        type: 'keystone',
        classType: PlayerClass.SWORDSMAN,
        icon: '⚔️',
        cost: 800,
        x: 910,
        y: 630,
        connections: ['sw_blood_siphon'],
        description: 'WARLORD KEYSTONE: +25% Magnet Radius, +20 Max HP, and kills extend invulnerability and frenzy duration.',
        stats: { pickupRadius: 1, maxHp: 20, damageBonus: 1 }
      }
    }
  },

  [PlayerClass.SORCERESS]: {
    classType: PlayerClass.SORCERESS,
    title: 'The Storm Weaver — 3 Elemental Archetypes',
    elementTitle: '⚡ Arcane Lightning & Frost',
    rootId: 'so_root',
    nodes: {
      so_root: {
        id: 'so_root',
        name: 'Arcane Leyline Core',
        type: 'root',
        classType: PlayerClass.SORCERESS,
        icon: '🔮',
        cost: 0,
        x: 500,
        y: 350,
        connections: ['so_cryo_minor_1', 'so_volt_minor_1', 'so_orb_minor_1', 'so_mana_1'],
        description: 'The primordial font of glacial frost and ionic lightning.',
        stats: { maxHp: 10 }
      },

      // --- BUILD A: GLACIAL CRYOMANCER (Top-Left) ---
      so_cryo_minor_1: {
        id: 'so_cryo_minor_1',
        name: 'Rime Crystal',
        type: 'minor',
        classType: PlayerClass.SORCERESS,
        icon: '❄️',
        cost: 95,
        x: 400,
        y: 260,
        connections: ['so_root', 'so_cryo_minor_2', 'so_volt_minor_1'],
        description: '+8% Elemental & Frost Damage.',
        stats: { damageBonus: 1 }
      },
      so_cryo_minor_2: {
        id: 'so_cryo_minor_2',
        name: 'Permafrost Chill',
        type: 'minor',
        classType: PlayerClass.SORCERESS,
        icon: '🧊',
        cost: 110,
        x: 320,
        y: 200,
        connections: ['so_cryo_minor_1', 'sorceress_frost', 'so_orb_minor_2'],
        description: '+10 Max HP. Frost spells slow enemies by an additional 15%.',
        stats: { maxHp: 10 }
      },
      sorceress_frost: {
        id: 'sorceress_frost',
        name: 'Frost Nova Surge',
        type: 'notable',
        classType: PlayerClass.SORCERESS,
        icon: '🧊',
        cost: 370,
        x: 230,
        y: 150,
        connections: ['so_cryo_minor_2', 'so_glacial_shatter'],
        description: 'BUILD A NOTABLE: Periodically unleashes a freezing shockwave. Rank 1 freezes for 1.0s, scaling to 1.8s with wider blast at Rank 3!',
        signatureSkillId: 'sorceress_frost',
        element: ElementType.LIGHTNING_FROST
      },
      so_glacial_shatter: {
        id: 'so_glacial_shatter',
        name: 'Glacial Shatter',
        type: 'notable',
        classType: PlayerClass.SORCERESS,
        icon: '❄️',
        cost: 390,
        x: 160,
        y: 110,
        connections: ['sorceress_frost', 'so_keystone_frost'],
        description: 'BUILD A NOTABLE: Slaying frozen monsters causes them to shatter into 6 piercing icicles dealing AoE damage.',
        signatureSkillId: 'so_glacial_shatter',
        element: ElementType.LIGHTNING_FROST
      },
      so_keystone_frost: {
        id: 'so_keystone_frost',
        name: 'Absolute Zero',
        type: 'keystone',
        classType: PlayerClass.SORCERESS,
        icon: '🧊',
        cost: 820,
        x: 90,
        y: 70,
        connections: ['so_glacial_shatter'],
        description: 'BUILD A KEYSTONE: +30 Max HP. Frozen foes take +50% amplified damage from all sources; freeze duration doubled.',
        stats: { maxHp: 30, damageBonus: 2 }
      },

      // --- BUILD B: IONIC OVERCHARGE & LIGHTNING (Top-Right) ---
      so_volt_minor_1: {
        id: 'so_volt_minor_1',
        name: 'Ionic Spark',
        type: 'minor',
        classType: PlayerClass.SORCERESS,
        icon: '⚡',
        cost: 95,
        x: 600,
        y: 260,
        connections: ['so_root', 'so_cryo_minor_1', 'so_volt_minor_2'],
        description: '+8% Lightning strike damage and chaining distance.',
        stats: { damageBonus: 1 }
      },
      so_volt_minor_2: {
        id: 'so_volt_minor_2',
        name: 'Static Conductor',
        type: 'minor',
        classType: PlayerClass.SORCERESS,
        icon: '🌩️',
        cost: 110,
        x: 680,
        y: 200,
        connections: ['so_volt_minor_1', 'sorceress_overcharge', 'so_speed_1'],
        description: '+6% Movement Speed & electrical critical resonance.',
        stats: { moveSpeed: 1 }
      },
      sorceress_overcharge: {
        id: 'sorceress_overcharge',
        name: 'Lightning Overcharge',
        type: 'notable',
        classType: PlayerClass.SORCERESS,
        icon: '⚡',
        cost: 370,
        x: 770,
        y: 150,
        connections: ['so_volt_minor_2', 'so_static_field'],
        description: 'BUILD B NOTABLE: Lightning chains to additional foes. Rank 1 arcs to 1 extra target, scaling to 3 targets with ionic detonation at Rank 3!',
        signatureSkillId: 'sorceress_overcharge',
        element: ElementType.LIGHTNING_FROST
      },
      so_static_field: {
        id: 'so_static_field',
        name: 'Static Field Pulse',
        type: 'notable',
        classType: PlayerClass.SORCERESS,
        icon: '✨',
        cost: 390,
        x: 840,
        y: 110,
        connections: ['sorceress_overcharge', 'so_keystone_tempest'],
        description: 'BUILD B NOTABLE: Every 4th lightning strike charges a radial electric field shocking all foes within 200 units.',
        signatureSkillId: 'so_static_field',
        element: ElementType.LIGHTNING_FROST
      },
      so_keystone_tempest: {
        id: 'so_keystone_tempest',
        name: 'Maelstrom Sovereign',
        type: 'keystone',
        classType: PlayerClass.SORCERESS,
        icon: '🌩️',
        cost: 820,
        x: 910,
        y: 70,
        connections: ['so_static_field'],
        description: 'BUILD B KEYSTONE: Chain lightning bounces have 50% greater range and each bounce triggers mini thunderbolts.',
        stats: { damageBonus: 2 }
      },

      // --- BUILD C: ORBITAL WARDEN (Bottom-Left) ---
      so_orb_minor_1: {
        id: 'so_orb_minor_1',
        name: 'Glacial Ward',
        type: 'minor',
        classType: PlayerClass.SORCERESS,
        icon: '🛡️',
        cost: 95,
        x: 400,
        y: 440,
        connections: ['so_root', 'so_orb_minor_2', 'so_mana_1'],
        description: '+2 Armor Defense via protective frost barrier.',
        stats: { defense: 1 }
      },
      so_orb_minor_2: {
        id: 'so_orb_minor_2',
        name: 'Orbital Affinity',
        type: 'minor',
        classType: PlayerClass.SORCERESS,
        icon: '❄️',
        cost: 115,
        x: 320,
        y: 500,
        connections: ['so_orb_minor_1', 'so_cryo_minor_2', 'sorceress_orbs'],
        description: '+2 Armor Defense & +10 Max HP.',
        stats: { defense: 1, maxHp: 10 }
      },
      sorceress_orbs: {
        id: 'sorceress_orbs',
        name: 'Orbital Frost Orbs',
        type: 'notable',
        classType: PlayerClass.SORCERESS,
        icon: '❄️',
        cost: 420,
        x: 230,
        y: 550,
        connections: ['so_orb_minor_2', 'so_astral_aegis'],
        description: 'BUILD C NOTABLE: Conjures orbiting glacial orbs dealing contact damage. Rank 1 grants 1 orb; Rank 2 grants 2 orbs!',
        signatureSkillId: 'sorceress_orbs',
        element: ElementType.LIGHTNING_FROST
      },
      so_astral_aegis: {
        id: 'so_astral_aegis',
        name: 'Astral Aegis',
        type: 'notable',
        classType: PlayerClass.SORCERESS,
        icon: '🔮',
        cost: 390,
        x: 160,
        y: 590,
        connections: ['sorceress_orbs', 'so_keystone_celestial'],
        description: 'BUILD C NOTABLE: Each active orb grants +3 Armor Defense and orbs periodically shoot out homing ice shards.',
        signatureSkillId: 'so_astral_aegis',
        element: ElementType.LIGHTNING_FROST
      },
      so_keystone_celestial: {
        id: 'so_keystone_celestial',
        name: 'Celestial Convergence',
        type: 'keystone',
        classType: PlayerClass.SORCERESS,
        icon: '👑',
        cost: 840,
        x: 90,
        y: 630,
        connections: ['so_astral_aegis'],
        description: 'BUILD C KEYSTONE: Orbs transform into rotating cosmic blades dealing 2x contact damage and shredding enemy armor.',
        stats: { defense: 2, maxHp: 30 }
      },

      // --- MANA RESERVOIR & SINGULARITY (Bottom-Right) ---
      so_mana_1: {
        id: 'so_mana_1',
        name: 'Astral Reservoir',
        type: 'minor',
        classType: PlayerClass.SORCERESS,
        icon: '❤️',
        cost: 95,
        x: 600,
        y: 440,
        connections: ['so_root', 'so_orb_minor_1', 'so_speed_1'],
        description: '+15 Max HP permanently.',
        stats: { maxHp: 15 }
      },
      so_speed_1: {
        id: 'so_speed_1',
        name: 'Aether Phase',
        type: 'minor',
        classType: PlayerClass.SORCERESS,
        icon: '💨',
        cost: 100,
        x: 680,
        y: 500,
        connections: ['so_mana_1', 'so_volt_minor_2', 'so_magnet_1'],
        description: '+6% Movement Speed.',
        stats: { moveSpeed: 1 }
      },
      so_magnet_1: {
        id: 'so_magnet_1',
        name: 'Leyline Siphon',
        type: 'minor',
        classType: PlayerClass.SORCERESS,
        icon: '🧲',
        cost: 110,
        x: 770,
        y: 550,
        connections: ['so_speed_1', 'so_spark_detonation'],
        description: '+25% EXP & Coin Magnet Radius.',
        stats: { pickupRadius: 1 }
      },
      so_spark_detonation: {
        id: 'so_spark_detonation',
        name: 'Spark Detonation',
        type: 'notable',
        classType: PlayerClass.SORCERESS,
        icon: '⚡',
        cost: 370,
        x: 840,
        y: 590,
        connections: ['so_magnet_1', 'so_keystone_singularity'],
        description: 'ASTRAL NOTABLE: Slaying shocked or frozen foes causes an ionic burst, restoring +2 HP and recharging spells faster.',
        signatureSkillId: 'so_spark_detonation',
        element: ElementType.LIGHTNING_FROST
      },
      so_keystone_singularity: {
        id: 'so_keystone_singularity',
        name: 'Astral Singularity',
        type: 'keystone',
        classType: PlayerClass.SORCERESS,
        icon: '🌟',
        cost: 800,
        x: 910,
        y: 630,
        connections: ['so_spark_detonation'],
        description: 'ASTRAL KEYSTONE: +25% Magnet Radius, +15 Max HP, and +10% All Elemental Damage.',
        stats: { pickupRadius: 1, maxHp: 15, damageBonus: 1 }
      }
    }
  },

  [PlayerClass.ARCHER]: {
    classType: PlayerClass.ARCHER,
    title: 'The Shadow Stalker — 3 Ballistic Archetypes',
    elementTitle: '🍃 Gale Force & Tempest Wind',
    rootId: 'ar_root',
    nodes: {
      ar_root: {
        id: 'ar_root',
        name: 'Eye of the Hawk',
        type: 'root',
        classType: PlayerClass.ARCHER,
        icon: '🏹',
        cost: 0,
        x: 500,
        y: 350,
        connections: ['ar_pierce_1', 'ar_multishot_minor_1', 'ar_evasion_1', 'ar_swift_1'],
        description: 'The ancient hunting root of the Shadow Stalker.',
        stats: { maxHp: 10 }
      },

      // --- BUILD A: TEMPEST SNIPER & BALLISTIC PIERCE (Top-Left) ---
      ar_pierce_1: {
        id: 'ar_pierce_1',
        name: 'Razor Feather',
        type: 'minor',
        classType: PlayerClass.ARCHER,
        icon: '🏹',
        cost: 95,
        x: 400,
        y: 260,
        connections: ['ar_root', 'ar_pierce_2', 'ar_multishot_minor_1'],
        description: '+8% All Damage & Arrow Velocity.',
        stats: { damageBonus: 1 }
      },
      ar_pierce_2: {
        id: 'ar_pierce_2',
        name: 'Sniper Focus',
        type: 'minor',
        classType: PlayerClass.ARCHER,
        icon: '🎯',
        cost: 110,
        x: 320,
        y: 200,
        connections: ['ar_pierce_1', 'ar_deadeye_pierce', 'ar_evasion_2'],
        description: '+10 Max HP & +6% Critical Strike Chance.',
        stats: { maxHp: 10 }
      },
      ar_deadeye_pierce: {
        id: 'ar_deadeye_pierce',
        name: 'Deadeye Longbow',
        type: 'notable',
        classType: PlayerClass.ARCHER,
        icon: '🎯',
        cost: 370,
        x: 230,
        y: 150,
        connections: ['ar_pierce_2', 'ar_ballistic_prec'],
        description: 'BUILD A NOTABLE: Arrows gain massive velocity and pierce through 2 ➔ 3 ➔ infinite monsters across 3 ranks!',
        signatureSkillId: 'ar_deadeye_pierce',
        element: ElementType.WIND_PIERCE
      },
      ar_ballistic_prec: {
        id: 'ar_ballistic_prec',
        name: 'Ballistic Precision',
        type: 'notable',
        classType: PlayerClass.ARCHER,
        icon: '🏹',
        cost: 390,
        x: 160,
        y: 110,
        connections: ['ar_deadeye_pierce', 'ar_keystone_sniper'],
        description: 'BUILD A NOTABLE: Arrows deal up to +50% more damage the further they travel before hitting target.',
        signatureSkillId: 'ar_ballistic_prec',
        element: ElementType.WIND_PIERCE
      },
      ar_keystone_sniper: {
        id: 'ar_keystone_sniper',
        name: 'Infinite Pierce Apex',
        type: 'keystone',
        classType: PlayerClass.ARCHER,
        icon: '🎯',
        cost: 820,
        x: 90,
        y: 70,
        connections: ['ar_ballistic_prec'],
        description: 'BUILD A KEYSTONE: Arrows pierce infinitely through all enemies and ricochet off map boundary barricades.',
        stats: { damageBonus: 2 }
      },

      // --- BUILD B: STORM MULTISHOT BARRAGE (Top-Right) ---
      ar_multishot_minor_1: {
        id: 'ar_multishot_minor_1',
        name: 'Windrunner Plume',
        type: 'minor',
        classType: PlayerClass.ARCHER,
        icon: '🍃',
        cost: 95,
        x: 600,
        y: 260,
        connections: ['ar_root', 'ar_pierce_1', 'ar_multishot_minor_2'],
        description: '+8% Damage with gale velocity.',
        stats: { damageBonus: 1 }
      },
      ar_multishot_minor_2: {
        id: 'ar_multishot_minor_2',
        name: 'Quiver of Gales',
        type: 'minor',
        classType: PlayerClass.ARCHER,
        icon: '🏹',
        cost: 110,
        x: 680,
        y: 200,
        connections: ['ar_multishot_minor_1', 'archer_multishot', 'ar_speed_1'],
        description: '+6% Movement Speed & tighter arrow spread.',
        stats: { moveSpeed: 1 }
      },
      archer_multishot: {
        id: 'archer_multishot',
        name: 'Gale Multishot',
        type: 'notable',
        classType: PlayerClass.ARCHER,
        icon: '🏹',
        cost: 380,
        x: 770,
        y: 150,
        connections: ['ar_multishot_minor_2', 'ar_rain_of_arrows'],
        description: 'BUILD B NOTABLE: Fires a spread fan of arrows. Rank 1 fires 2 arrows, Rank 2 fires 3 arrows, Rank 3 fires 4 sweeping arrows!',
        signatureSkillId: 'archer_multishot',
        element: ElementType.WIND_PIERCE
      },
      ar_rain_of_arrows: {
        id: 'ar_rain_of_arrows',
        name: 'Rain of Arrows',
        type: 'notable',
        classType: PlayerClass.ARCHER,
        icon: '🌧️',
        cost: 400,
        x: 840,
        y: 110,
        connections: ['archer_multishot', 'ar_keystone_barrage'],
        description: 'BUILD B NOTABLE: Every 6th volley triggers a localized rain of 12 shadow arrows shredding a targeted area.',
        signatureSkillId: 'ar_rain_of_arrows',
        element: ElementType.WIND_PIERCE
      },
      ar_keystone_barrage: {
        id: 'ar_keystone_barrage',
        name: 'Tempest Barrage',
        type: 'keystone',
        classType: PlayerClass.ARCHER,
        icon: '🌪️',
        cost: 820,
        x: 910,
        y: 70,
        connections: ['ar_rain_of_arrows'],
        description: 'BUILD B KEYSTONE: On critical strike, Multishot discharges a full 360° ring of piercing arrows around the Archer.',
        stats: { damageBonus: 2 }
      },

      // --- BUILD C: LIGHTNING TRAPPER & WINDRUNNER (Bottom-Left) ---
      ar_evasion_1: {
        id: 'ar_evasion_1',
        name: 'Whispering Cloak',
        type: 'minor',
        classType: PlayerClass.ARCHER,
        icon: '🛡️',
        cost: 95,
        x: 400,
        y: 440,
        connections: ['ar_root', 'ar_evasion_2', 'ar_swift_1'],
        description: '+2 Armor Defense and agile deflection.',
        stats: { defense: 1 }
      },
      ar_evasion_2: {
        id: 'ar_evasion_2',
        name: 'Phantom Shift',
        type: 'minor',
        classType: PlayerClass.ARCHER,
        icon: '💨',
        cost: 115,
        x: 320,
        y: 500,
        connections: ['ar_evasion_1', 'ar_pierce_2', 'archer_windrunner'],
        description: '+2 Armor Defense & +10 Max HP.',
        stats: { defense: 1, maxHp: 10 }
      },
      archer_windrunner: {
        id: 'archer_windrunner',
        name: 'Windrunner Phantom',
        type: 'notable',
        classType: PlayerClass.ARCHER,
        icon: '💨',
        cost: 350,
        x: 230,
        y: 550,
        connections: ['ar_evasion_2', 'ar_static_caltrops'],
        description: 'BUILD C NOTABLE: +Move Speed and 10% ➔ 18% ➔ 25% chance to completely evade incoming enemy strikes across 3 ranks!',
        signatureSkillId: 'archer_windrunner',
        element: ElementType.WIND_PIERCE
      },
      ar_static_caltrops: {
        id: 'ar_static_caltrops',
        name: 'Static Caltrops',
        type: 'notable',
        classType: PlayerClass.ARCHER,
        icon: '⚡',
        cost: 390,
        x: 160,
        y: 590,
        connections: ['archer_windrunner', 'ar_keystone_phantom'],
        description: 'BUILD C NOTABLE: Leaves shocking caltrops behind while moving that slow and electrocute pursuers.',
        signatureSkillId: 'ar_static_caltrops',
        element: ElementType.WIND_PIERCE
      },
      ar_keystone_phantom: {
        id: 'ar_keystone_phantom',
        name: 'Phantom Step Apex',
        type: 'keystone',
        classType: PlayerClass.ARCHER,
        icon: '🍃',
        cost: 820,
        x: 90,
        y: 630,
        connections: ['ar_static_caltrops'],
        description: 'BUILD C KEYSTONE: +8% Move Speed, +30 Max HP. Evading damage triggers a burst of wind blades damaging attackers.',
        stats: { moveSpeed: 1, maxHp: 30, defense: 1 }
      },

      // --- LIGHTNING ARROWS & SUPERCONDUCTOR (Bottom-Right) ---
      ar_swift_1: {
        id: 'ar_swift_1',
        name: 'Stalker Stride',
        type: 'minor',
        classType: PlayerClass.ARCHER,
        icon: '❤️',
        cost: 95,
        x: 600,
        y: 440,
        connections: ['ar_root', 'ar_evasion_1', 'ar_speed_1'],
        description: '+15 Max HP permanently.',
        stats: { maxHp: 15 }
      },
      ar_speed_1: {
        id: 'ar_speed_1',
        name: 'Zephyr Agility',
        type: 'minor',
        classType: PlayerClass.ARCHER,
        icon: '💨',
        cost: 100,
        x: 680,
        y: 500,
        connections: ['ar_swift_1', 'ar_multishot_minor_2', 'ar_magnet_1'],
        description: '+6% Movement Speed.',
        stats: { moveSpeed: 1 }
      },
      ar_magnet_1: {
        id: 'ar_magnet_1',
        name: 'Gale Vortex Magnet',
        type: 'minor',
        classType: PlayerClass.ARCHER,
        icon: '🧲',
        cost: 110,
        x: 770,
        y: 550,
        connections: ['ar_speed_1', 'archer_lightning'],
        description: '+25% EXP & Coin Magnet Radius.',
        stats: { pickupRadius: 1 }
      },
      archer_lightning: {
        id: 'archer_lightning',
        name: 'Lightning Arrow',
        type: 'notable',
        classType: PlayerClass.ARCHER,
        icon: '⚡',
        cost: 380,
        x: 840,
        y: 590,
        connections: ['ar_magnet_1', 'ar_keystone_superconductor'],
        description: 'LIGHTNING NOTABLE: Arrows shock foes on hit. Rank 1 has 30% proc chance (1 foe), scaling to 100% (3 foes) at Rank 3!',
        signatureSkillId: 'archer_lightning',
        element: ElementType.WIND_PIERCE
      },
      ar_keystone_superconductor: {
        id: 'ar_keystone_superconductor',
        name: 'Superconductor Surge',
        type: 'keystone',
        classType: PlayerClass.ARCHER,
        icon: '🌩️',
        cost: 820,
        x: 910,
        y: 630,
        connections: ['archer_lightning'],
        description: 'LIGHTNING KEYSTONE: Lightning chains generate static charges; at 10 charges, releases a screen-clearing catastrophic thunderbolt!',
        stats: { pickupRadius: 1, maxHp: 15, damageBonus: 1 }
      }
    }
  },

  [PlayerClass.CLERIC]: {
    classType: PlayerClass.CLERIC,
    title: 'The Radiant Arbiter — 3 Divine Archetypes',
    elementTitle: '✨ Solar Dawn & Holy Divinity',
    rootId: 'cl_root',
    nodes: {
      cl_root: {
        id: 'cl_root',
        name: 'Altar of the Dawn',
        type: 'root',
        classType: PlayerClass.CLERIC,
        icon: '✝️',
        cost: 0,
        x: 500,
        y: 350,
        connections: ['cl_holy_1', 'cl_radiance_1', 'cl_armor_1', 'cl_faith_1'],
        description: 'The celestial sanctuary altar of the Radiant Arbiter.',
        stats: { maxHp: 10 }
      },

      // --- BUILD A: LUMINARY SHEPHERD & GROUP HEAL (Top-Left) ---
      cl_holy_1: {
        id: 'cl_holy_1',
        name: 'Consecrated Light',
        type: 'minor',
        classType: PlayerClass.CLERIC,
        icon: '✨',
        cost: 95,
        x: 400,
        y: 260,
        connections: ['cl_root', 'cl_holy_2', 'cl_radiance_1'],
        description: '+8% Holy Smite & Divine Damage.',
        stats: { damageBonus: 1 }
      },
      cl_holy_2: {
        id: 'cl_holy_2',
        name: 'Aura of Grace',
        type: 'minor',
        classType: PlayerClass.CLERIC,
        icon: '🌟',
        cost: 110,
        x: 320,
        y: 200,
        connections: ['cl_holy_1', 'cleric_heal_aura', 'cl_armor_2'],
        description: '+10 Max HP & +15% healing pulse reach.',
        stats: { maxHp: 10 }
      },
      cleric_heal_aura: {
        id: 'cleric_heal_aura',
        name: 'Holy Radiance Aura',
        type: 'notable',
        classType: PlayerClass.CLERIC,
        icon: '✨',
        cost: 380,
        x: 230,
        y: 150,
        connections: ['cl_holy_2', 'cl_sanctified_swiftness'],
        description: 'BUILD A NOTABLE: Emits a golden aura healing self and co-op allies while scorching foes. Scales across 3 ranks!',
        signatureSkillId: 'cleric_heal_aura',
        element: ElementType.HOLY_LIGHT
      },
      cl_sanctified_swiftness: {
        id: 'cl_sanctified_swiftness',
        name: 'Sanctified Swiftness',
        type: 'notable',
        classType: PlayerClass.CLERIC,
        icon: '🕊️',
        cost: 390,
        x: 160,
        y: 110,
        connections: ['cleric_heal_aura', 'cl_keystone_benediction'],
        description: 'BUILD A NOTABLE: Holy Radiance grants +15% movement speed to all nearby party members; revive time reduced by 50%.',
        signatureSkillId: 'cl_sanctified_swiftness',
        element: ElementType.HOLY_LIGHT
      },
      cl_keystone_benediction: {
        id: 'cl_keystone_benediction',
        name: 'Divine Benediction',
        type: 'keystone',
        classType: PlayerClass.CLERIC,
        icon: '☀️',
        cost: 820,
        x: 90,
        y: 70,
        connections: ['cl_sanctified_swiftness'],
        description: 'BUILD A KEYSTONE: +30 Max HP. Healing that exceeds Max HP converts into a golden protective barrier absorbing up to 30% bonus health!',
        stats: { maxHp: 30, damageBonus: 2 }
      },

      // --- BUILD B: DIVINE ORACLE & PILLARS OF WRATH (Top-Right) ---
      cl_radiance_1: {
        id: 'cl_radiance_1',
        name: 'Sunfire Brand',
        type: 'minor',
        classType: PlayerClass.CLERIC,
        icon: '🔥',
        cost: 95,
        x: 600,
        y: 260,
        connections: ['cl_root', 'cl_holy_1', 'cl_radiance_2'],
        description: '+8% All Damage and solar burn magnitude.',
        stats: { damageBonus: 1 }
      },
      cl_radiance_2: {
        id: 'cl_radiance_2',
        name: 'Solar Wrath',
        type: 'minor',
        classType: PlayerClass.CLERIC,
        icon: '⚡',
        cost: 110,
        x: 680,
        y: 200,
        connections: ['cl_radiance_1', 'cleric_judgment', 'cl_speed_1'],
        description: '+6% Movement Speed & holy critical force.',
        stats: { moveSpeed: 1 }
      },
      cleric_judgment: {
        id: 'cleric_judgment',
        name: 'Divine Judgment',
        type: 'notable',
        classType: PlayerClass.CLERIC,
        icon: '⚡',
        cost: 400,
        x: 770,
        y: 150,
        connections: ['cl_radiance_2', 'cl_wrath_heavens'],
        description: 'BUILD B NOTABLE: Calls down celestial pillars crushing random monsters. Rank 1 calls 1 pillar, scaling to 3 pillars at Rank 3!',
        signatureSkillId: 'cleric_judgment',
        element: ElementType.HOLY_LIGHT
      },
      cl_wrath_heavens: {
        id: 'cl_wrath_heavens',
        name: 'Wrath of the Heavens',
        type: 'notable',
        classType: PlayerClass.CLERIC,
        icon: '⚖️',
        cost: 400,
        x: 840,
        y: 110,
        connections: ['cleric_judgment', 'cl_keystone_archangel'],
        description: 'BUILD B NOTABLE: Judgment pillars leave scorched ground burning monsters for 3.0s and dealing +25% holy damage.',
        signatureSkillId: 'cl_wrath_heavens',
        element: ElementType.HOLY_LIGHT
      },
      cl_keystone_archangel: {
        id: 'cl_keystone_archangel',
        name: 'Cataclysm of the Archangel',
        type: 'keystone',
        classType: PlayerClass.CLERIC,
        icon: '👑',
        cost: 840,
        x: 910,
        y: 70,
        connections: ['cl_wrath_heavens'],
        description: 'BUILD B KEYSTONE: Judgment pillars trigger secondary shockwaves that pull enemies toward the pillar center before exploding.',
        stats: { damageBonus: 2 }
      },

      // --- BUILD C: SOLAR PALADIN & AEGIS (Bottom-Left) ---
      cl_armor_1: {
        id: 'cl_armor_1',
        name: 'Blessed Mail',
        type: 'minor',
        classType: PlayerClass.CLERIC,
        icon: '🛡️',
        cost: 95,
        x: 400,
        y: 440,
        connections: ['cl_root', 'cl_armor_2', 'cl_faith_1'],
        description: '+2 Armor Defense.',
        stats: { defense: 1 }
      },
      cl_armor_2: {
        id: 'cl_armor_2',
        name: 'Shield of Faith',
        type: 'minor',
        classType: PlayerClass.CLERIC,
        icon: '🛡️',
        cost: 115,
        x: 320,
        y: 500,
        connections: ['cl_armor_1', 'cl_holy_2', 'cleric_aegis'],
        description: '+2 Armor Defense & +10 Max HP.',
        stats: { defense: 1, maxHp: 10 }
      },
      cleric_aegis: {
        id: 'cleric_aegis',
        name: 'Blessed Aegis',
        type: 'notable',
        classType: PlayerClass.CLERIC,
        icon: '🛡️',
        cost: 360,
        x: 230,
        y: 550,
        connections: ['cl_armor_2', 'cl_consecrated_ground'],
        description: 'BUILD C NOTABLE: +Armor Defense and provides a golden ward absorbing damage. Scales across 3 ranks!',
        signatureSkillId: 'cleric_aegis',
        element: ElementType.HOLY_LIGHT
      },
      cl_consecrated_ground: {
        id: 'cl_consecrated_ground',
        name: 'Consecrated Ground',
        type: 'notable',
        classType: PlayerClass.CLERIC,
        icon: '⛪',
        cost: 380,
        x: 160,
        y: 590,
        connections: ['cleric_aegis', 'cl_keystone_sanctuary'],
        description: 'BUILD C NOTABLE: Walking blesses the ground beneath the Cleric, healing standing allies and burning evil monsters.',
        signatureSkillId: 'cl_consecrated_ground',
        element: ElementType.HOLY_LIGHT
      },
      cl_keystone_sanctuary: {
        id: 'cl_keystone_sanctuary',
        name: 'Impervious Sanctuary',
        type: 'keystone',
        classType: PlayerClass.CLERIC,
        icon: '🏰',
        cost: 820,
        x: 90,
        y: 630,
        connections: ['cl_consecrated_ground'],
        description: 'BUILD C KEYSTONE: +5 Armor Defense and +30 Max HP. When health drops below 30%, releases an instant 100% healing burst!',
        stats: { defense: 2, maxHp: 30 }
      },

      // --- FAITH & TITHE (Bottom-Right) ---
      cl_faith_1: {
        id: 'cl_faith_1',
        name: 'Vessel of Grace',
        type: 'minor',
        classType: PlayerClass.CLERIC,
        icon: '❤️',
        cost: 95,
        x: 600,
        y: 440,
        connections: ['cl_root', 'cl_armor_1', 'cl_speed_1'],
        description: '+15 Max HP permanently.',
        stats: { maxHp: 15 }
      },
      cl_speed_1: {
        id: 'cl_speed_1',
        name: 'Pilgrim Zeal',
        type: 'minor',
        classType: PlayerClass.CLERIC,
        icon: '💨',
        cost: 100,
        x: 680,
        y: 500,
        connections: ['cl_faith_1', 'cl_radiance_2', 'cl_magnet_1'],
        description: '+6% Movement Speed.',
        stats: { moveSpeed: 1 }
      },
      cl_magnet_1: {
        id: 'cl_magnet_1',
        name: 'Grace Collector Magnet',
        type: 'minor',
        classType: PlayerClass.CLERIC,
        icon: '🧲',
        cost: 110,
        x: 770,
        y: 550,
        connections: ['cl_speed_1', 'cl_heavenly_retrib'],
        description: '+25% EXP & Coin Magnet Radius.',
        stats: { pickupRadius: 1 }
      },
      cl_heavenly_retrib: {
        id: 'cl_heavenly_retrib',
        name: 'Heavenly Retribution',
        type: 'notable',
        classType: PlayerClass.CLERIC,
        icon: '☀️',
        cost: 370,
        x: 840,
        y: 590,
        connections: ['cl_magnet_1', 'cl_keystone_providence'],
        description: 'RETRIBUTION NOTABLE: Taking damage triggers a solar counter-blast knocking back and blinding attackers.',
        signatureSkillId: 'cl_heavenly_retrib',
        element: ElementType.HOLY_LIGHT
      },
      cl_keystone_providence: {
        id: 'cl_keystone_providence',
        name: 'Divine Providence',
        type: 'keystone',
        classType: PlayerClass.CLERIC,
        icon: '🌟',
        cost: 800,
        x: 910,
        y: 630,
        connections: ['cl_heavenly_retrib'],
        description: 'RETRIBUTION KEYSTONE: +25% Magnet Radius, +15 Max HP, and +10% All Holy Damage.',
        stats: { pickupRadius: 1, maxHp: 15, damageBonus: 1 }
      }
    }
  },

  [PlayerClass.COMMANDO]: {
    classType: PlayerClass.COMMANDO,
    title: 'Tactical Vanguard — Special Warfare Mastery Web',
    elementTitle: '💣 Ballistic High-Explosive & AP Ballistics',
    rootId: 'cmd_root',
    nodes: {
      cmd_root: {
        id: 'cmd_root',
        name: 'Vanguard Headquarters (ศูนย์บัญชาการ)',
        type: 'root',
        classType: PlayerClass.COMMANDO,
        icon: '🎖️',
        cost: 0,
        x: 500,
        y: 350,
        connections: ['cmd_frag_minor', 'cmd_ap_minor', 'cmd_hp_minor', 'cmd_speed_minor'],
        description: 'Military command center of the Tactical Vanguard. Starting origin root.',
        stats: { maxHp: 15 }
      },

      // --- BUILD A: HIGH-EXPLOSIVE & ARTILLERY (Top-Left) ---
      cmd_frag_minor: {
        id: 'cmd_frag_minor',
        name: 'Munitions Conditioning (ปรับแต่งดินระเบิด)',
        type: 'minor',
        classType: PlayerClass.COMMANDO,
        icon: '🧨',
        cost: 95,
        x: 390,
        y: 260,
        connections: ['cmd_root', 'commando_frag_grenade', 'cmd_radius_minor'],
        description: '+8 Flat Damage and explosive radius expansion.',
        stats: { damageBonus: 1 }
      },
      cmd_radius_minor: {
        id: 'cmd_radius_minor',
        name: 'Blast Radius (ขยายรัศมีแรงอัด)',
        type: 'minor',
        classType: PlayerClass.COMMANDO,
        icon: '💥',
        cost: 110,
        x: 290,
        y: 280,
        connections: ['cmd_frag_minor', 'cmd_napalm', 'cmd_shrapnel_1'],
        description: '+15% Area of effect for all grenades and airstrikes.',
        stats: { damageBonus: 1 }
      },
      commando_frag_grenade: {
        id: 'commando_frag_grenade',
        name: 'Frag Grenade Satchel (ระเบิดลูกปราย)',
        type: 'notable',
        classType: PlayerClass.COMMANDO,
        icon: '💣',
        cost: 360,
        x: 300,
        y: 190,
        connections: ['cmd_frag_minor', 'cmd_shrapnel_1'],
        description: 'NOTABLE: Tosses high-explosive frag grenades periodically that blast clusters of foes into shrapnel.',
        signatureSkillId: 'commando_frag_grenade',
        element: ElementType.BALLISTIC_FIRE
      },
      cmd_shrapnel_1: {
        id: 'cmd_shrapnel_1',
        name: 'Thermite Shrapnel (สะเก็ดเพลิง)',
        type: 'minor',
        classType: PlayerClass.COMMANDO,
        icon: '🔥',
        cost: 135,
        x: 210,
        y: 130,
        connections: ['commando_frag_grenade', 'cmd_radius_minor', 'commando_airstrike'],
        description: '+12 Flat Damage and burning ignite ticks on explosive impact.',
        stats: { damageBonus: 2 }
      },
      cmd_napalm: {
        id: 'cmd_napalm',
        name: 'Napalm Cluster (ระเบิดเพลิงนาปาล์ม)',
        type: 'notable',
        classType: PlayerClass.COMMANDO,
        icon: '☄️',
        cost: 380,
        x: 200,
        y: 230,
        connections: ['cmd_radius_minor', 'commando_airstrike'],
        description: 'NOTABLE: Explosives leave scorching napalm fire puddles that burn crossing enemies.',
        element: ElementType.BALLISTIC_FIRE,
        stats: { damageBonus: 2 }
      },
      commando_airstrike: {
        id: 'commando_airstrike',
        name: 'Precision Airstrike (การโจมตีทางอากาศ)',
        type: 'keystone',
        classType: PlayerClass.COMMANDO,
        icon: '✈️',
        cost: 450,
        x: 120,
        y: 80,
        connections: ['cmd_shrapnel_1', 'cmd_napalm'],
        description: 'KEYSTONE: Calls down orbital laser-guided smart bombs periodically dealing catastrophic destruction across the battlefield.',
        signatureSkillId: 'commando_airstrike',
        element: ElementType.BALLISTIC_FIRE
      },

      // --- BUILD B: AP BALLISTICS & RAPID FIRE (Top-Right) ---
      cmd_ap_minor: {
        id: 'cmd_ap_minor',
        name: 'Tungsten AP Core (กระสุนเจาะเกราะ)',
        type: 'minor',
        classType: PlayerClass.COMMANDO,
        icon: '🎯',
        cost: 95,
        x: 610,
        y: 260,
        connections: ['cmd_root', 'commando_ap_rounds', 'cmd_recoil_minor'],
        description: 'M4A1 rounds pierce through +1 additional monster with +10% projectile speed.',
        stats: { damageBonus: 1 }
      },
      cmd_recoil_minor: {
        id: 'cmd_recoil_minor',
        name: 'Recoil Compensator (ลดแรงดีด)',
        type: 'minor',
        classType: PlayerClass.COMMANDO,
        icon: '⚙️',
        cost: 110,
        x: 710,
        y: 280,
        connections: ['cmd_ap_minor', 'cmd_bullet_fury', 'cmd_fire_rate_1'],
        description: '+10% Attack Speed and +5% Movement Speed while firing.',
        stats: { moveSpeed: 1 }
      },
      commando_ap_rounds: {
        id: 'commando_ap_rounds',
        name: 'High-Caliber AP (หัวกระสุนทังสเตน)',
        type: 'notable',
        classType: PlayerClass.COMMANDO,
        icon: '🔫',
        cost: 360,
        x: 700,
        y: 190,
        connections: ['cmd_ap_minor', 'cmd_fire_rate_1'],
        description: 'NOTABLE: Greatly enhances bullet penetration, shredding heavy monster armor on impact.',
        signatureSkillId: 'commando_ap_rounds',
        element: ElementType.BALLISTIC_FIRE
      },
      cmd_fire_rate_1: {
        id: 'cmd_fire_rate_1',
        name: 'Heavy Barrel Rifling (เกลียวลำกล้องคู่)',
        type: 'minor',
        classType: PlayerClass.COMMANDO,
        icon: '⚡',
        cost: 135,
        x: 790,
        y: 130,
        connections: ['commando_ap_rounds', 'cmd_recoil_minor', 'commando_tactical_reload'],
        description: '+15 Flat Damage and +12% Attack Speed.',
        stats: { damageBonus: 2 }
      },
      cmd_bullet_fury: {
        id: 'cmd_bullet_fury',
        name: 'Suppressing Fire (กระหน่ำยิงกดดัน)',
        type: 'notable',
        classType: PlayerClass.COMMANDO,
        icon: '🔥',
        cost: 380,
        x: 800,
        y: 230,
        connections: ['cmd_recoil_minor', 'commando_tactical_reload'],
        description: 'NOTABLE: Rapid ballistic bursts cause monsters to slow by 35% and stagger.',
        stats: { damageBonus: 2 }
      },
      commando_tactical_reload: {
        id: 'commando_tactical_reload',
        name: 'Tactical Mag Reloader (รีโหลดฉับพลัน)',
        type: 'keystone',
        classType: PlayerClass.COMMANDO,
        icon: '🔄',
        cost: 450,
        x: 880,
        y: 80,
        connections: ['cmd_fire_rate_1', 'cmd_bullet_fury'],
        description: 'KEYSTONE: Eliminates fire delay interruptions, boosting fire rate by +35% and unleashing continuous lead torrents.',
        signatureSkillId: 'commando_tactical_reload',
        element: ElementType.BALLISTIC_FIRE
      },

      // --- BUILD C: SURVIVALIST & JUGGERNAUT (Bottom) ---
      cmd_hp_minor: {
        id: 'cmd_hp_minor',
        name: 'Kevlar Weave (เกราะเคฟลาร์)',
        type: 'minor',
        classType: PlayerClass.COMMANDO,
        icon: '🛡️',
        cost: 100,
        x: 430,
        y: 440,
        connections: ['cmd_root', 'cmd_kevlar', 'cmd_speed_minor'],
        description: '+15 Max HP and +1 Flat Defense.',
        stats: { maxHp: 15, defense: 1 }
      },
      cmd_speed_minor: {
        id: 'cmd_speed_minor',
        name: 'Tactical Sprint (วิ่งแทคติคอล)',
        type: 'minor',
        classType: PlayerClass.COMMANDO,
        icon: '👟',
        cost: 100,
        x: 570,
        y: 440,
        connections: ['cmd_root', 'cmd_combat_boots', 'cmd_hp_minor'],
        description: '+10% Movement Speed and +15% Dash Recovery.',
        stats: { moveSpeed: 1 }
      },
      cmd_kevlar: {
        id: 'cmd_kevlar',
        name: 'Ceramic Trauma Plates (แผ่นเกราะเซรามิก)',
        type: 'notable',
        classType: PlayerClass.COMMANDO,
        icon: '🦺',
        cost: 320,
        x: 360,
        y: 520,
        connections: ['cmd_hp_minor', 'cmd_adrenaline', 'cmd_juggernaut'],
        description: 'NOTABLE: Reduces direct monster damage taken by 15% and grants immunity to pushback.',
        stats: { defense: 2, maxHp: 20 }
      },
      cmd_combat_boots: {
        id: 'cmd_combat_boots',
        name: 'Vanguard Exosuit (โครงเสริมกำลังรบ)',
        type: 'notable',
        classType: PlayerClass.COMMANDO,
        icon: '🦿',
        cost: 320,
        x: 640,
        y: 520,
        connections: ['cmd_speed_minor', 'cmd_last_stand', 'cmd_juggernaut'],
        description: 'NOTABLE: Grants +15% Move Speed and magnetic pickup radius for dropped ammo and items.',
        stats: { moveSpeed: 1, pickupRadius: 1 }
      },
      cmd_adrenaline: {
        id: 'cmd_adrenaline',
        name: 'Combat Adrenaline (อะดรีนาลีนสงคราม)',
        type: 'minor',
        classType: PlayerClass.COMMANDO,
        icon: '💉',
        cost: 150,
        x: 300,
        y: 600,
        connections: ['cmd_kevlar', 'cmd_juggernaut'],
        description: '+25 Max HP and triggers quick HP regen when below 40% health.',
        stats: { maxHp: 25 }
      },
      cmd_last_stand: {
        id: 'cmd_last_stand',
        name: 'Last Stand Protocol (คำสั่งสู้ตาย)',
        type: 'minor',
        classType: PlayerClass.COMMANDO,
        icon: '🎖️',
        cost: 150,
        x: 700,
        y: 600,
        connections: ['cmd_combat_boots', 'cmd_juggernaut'],
        description: '+20% Attack Speed and +2 Flat Defense when surrounded.',
        stats: { defense: 2 }
      },
      cmd_juggernaut: {
        id: 'cmd_juggernaut',
        name: 'Apex Warfighter (สุดยอดทหารศึก)',
        type: 'keystone',
        classType: PlayerClass.COMMANDO,
        icon: '🦾',
        cost: 450,
        x: 500,
        y: 630,
        connections: ['cmd_kevlar', 'cmd_combat_boots', 'cmd_adrenaline', 'cmd_last_stand'],
        description: 'KEYSTONE: Transforms the commando into an unstoppable war machine with +50 Max HP, +3 Defense, and permanent 15% damage reduction.',
        stats: { maxHp: 50, defense: 3 }
      }
    }
  },

  [PlayerClass.CAT_TANK]: {
    classType: PlayerClass.CAT_TANK,
    title: 'The Feline Bastion — Titan Chonk Mastery Web',
    elementTitle: '🐾 Seismic Impact & Toxic Hairball Bio',
    rootId: 'cat_root',
    nodes: {
      cat_root: {
        id: 'cat_root',
        name: 'Cat Castle Core (ปราสาทแมวเหมียว)',
        type: 'root',
        classType: PlayerClass.CAT_TANK,
        icon: '🐱',
        cost: 0,
        x: 500,
        y: 350,
        connections: ['cat_slam_minor', 'cat_spit_minor', 'cat_def_minor', 'cat_taunt_minor'],
        description: 'The cozy scratching post of the Cat Tank. Starting origin root.',
        stats: { maxHp: 25 }
      },

      // --- BUILD A: TITAN SEISMIC SLAM (Top-Left) ---
      cat_slam_minor: {
        id: 'cat_slam_minor',
        name: 'Heavy Paws (อุ้งมือทรงพลัง)',
        type: 'minor',
        classType: PlayerClass.CAT_TANK,
        icon: '🐾',
        cost: 95,
        x: 390,
        y: 260,
        connections: ['cat_root', 'cattank_chonk_armor', 'cat_aoe_minor'],
        description: '+10 Flat Damage and +15% Paw Slam reach.',
        stats: { damageBonus: 1 }
      },
      cat_aoe_minor: {
        id: 'cat_aoe_minor',
        name: 'Chonk Radius (รัศมีความอ้วน)',
        type: 'minor',
        classType: PlayerClass.CAT_TANK,
        icon: '💥',
        cost: 110,
        x: 290,
        y: 280,
        connections: ['cat_slam_minor', 'cat_belly_flop', 'cat_seismic_1'],
        description: '+20% Area of effect for all ground slams and shockwaves.',
        stats: { damageBonus: 1 }
      },
      cattank_chonk_armor: {
        id: 'cattank_chonk_armor',
        name: 'Titan Chonk Armor (เกราะไขมันหนานุ่ม)',
        type: 'notable',
        classType: PlayerClass.CAT_TANK,
        icon: '🛡️',
        cost: 360,
        x: 300,
        y: 190,
        connections: ['cat_slam_minor', 'cat_seismic_1'],
        description: 'NOTABLE: Massive blubber cushions monster hits, granting +40 Max HP and +2 Flat Defense.',
        signatureSkillId: 'cattank_chonk_armor',
        element: ElementType.CHONK_FORTRESS,
        stats: { maxHp: 40, defense: 2 }
      },
      cat_seismic_1: {
        id: 'cat_seismic_1',
        name: 'Seismic Claws (กรงเล็บแผ่นดินไหว)',
        type: 'minor',
        classType: PlayerClass.CAT_TANK,
        icon: '⚡',
        cost: 135,
        x: 210,
        y: 130,
        connections: ['cattank_chonk_armor', 'cat_aoe_minor', 'cat_titan_quake'],
        description: '+15 Flat Damage and paw slams crack the ground with shock ripples.',
        stats: { damageBonus: 2 }
      },
      cat_belly_flop: {
        id: 'cat_belly_flop',
        name: 'Colossal Belly Flop (พุงทิ้งดิ่ง)',
        type: 'notable',
        classType: PlayerClass.CAT_TANK,
        icon: '🦭',
        cost: 380,
        x: 200,
        y: 230,
        connections: ['cat_aoe_minor', 'cat_titan_quake'],
        description: 'NOTABLE: Ground slams knockback all surrounding enemies by 60 units with heavy stun.',
        stats: { damageBonus: 2 }
      },
      cat_titan_quake: {
        id: 'cat_titan_quake',
        name: 'Titan Earthshaker (มหาแผ่นดินไหวไททัน)',
        type: 'keystone',
        classType: PlayerClass.CAT_TANK,
        icon: '🌋',
        cost: 450,
        x: 120,
        y: 80,
        connections: ['cat_seismic_1', 'cat_belly_flop'],
        description: 'KEYSTONE: Paw Slams shake the entire dungeon screen, dealing double damage and leaving fissures that crush foes.',
        element: ElementType.CHONK_FORTRESS
      },

      // --- BUILD B: TOXIC HAIRBALL ARTILLERY (Top-Right) ---
      cat_spit_minor: {
        id: 'cat_spit_minor',
        name: 'Acid Saliva (น้ำลายกรดเข้มข้น)',
        type: 'minor',
        classType: PlayerClass.CAT_TANK,
        icon: '🧪',
        cost: 95,
        x: 610,
        y: 260,
        connections: ['cat_root', 'cattank_hairball', 'cat_digest_minor'],
        description: 'Increases hairball flight speed by +25% and damage by +10.',
        stats: { damageBonus: 1 }
      },
      cat_digest_minor: {
        id: 'cat_digest_minor',
        name: 'Fur Ball Storage (คลังเก็บก้อนขน)',
        type: 'minor',
        classType: PlayerClass.CAT_TANK,
        icon: '🧶',
        cost: 110,
        x: 710,
        y: 280,
        connections: ['cat_spit_minor', 'cat_furball_frenzy', 'cat_acid_pool'],
        description: 'Hairballs pierce +1 additional monster and burst into acid shards.',
        stats: { damageBonus: 1 }
      },
      cattank_hairball: {
        id: 'cattank_hairball',
        name: 'Hairball Launcher (เครื่องยิงก้อนขนกรด)',
        type: 'notable',
        classType: PlayerClass.CAT_TANK,
        icon: '🤮',
        cost: 360,
        x: 700,
        y: 190,
        connections: ['cat_spit_minor', 'cat_acid_pool'],
        description: 'NOTABLE: Spits toxic acidic fur balls periodically that melt armored foes.',
        signatureSkillId: 'cattank_hairball',
        element: ElementType.CHONK_FORTRESS
      },
      cat_acid_pool: {
        id: 'cat_acid_pool',
        name: 'Corrosive Puddle (บ่อกรดกัดกร่อน)',
        type: 'minor',
        classType: PlayerClass.CAT_TANK,
        icon: '🟢',
        cost: 135,
        x: 790,
        y: 130,
        connections: ['cattank_hairball', 'cat_digest_minor', 'cat_hairball_gatling'],
        description: 'Hairballs create corrosive acid pools dealing ticking damage for 4 seconds.',
        stats: { damageBonus: 2 }
      },
      cat_furball_frenzy: {
        id: 'cat_furball_frenzy',
        name: 'Coughing Fit (สำลักก้อนขนรัว)',
        type: 'notable',
        classType: PlayerClass.CAT_TANK,
        icon: '🤢',
        cost: 380,
        x: 800,
        y: 230,
        connections: ['cat_digest_minor', 'cat_hairball_gatling'],
        description: 'NOTABLE: Hairballs fire in a fan of 3 projectiles instead of 1.',
        element: ElementType.CHONK_FORTRESS
      },
      cat_hairball_gatling: {
        id: 'cat_hairball_gatling',
        name: 'Gatling Vomit (ปืนกลก้อนขนพิษ)',
        type: 'keystone',
        classType: PlayerClass.CAT_TANK,
        icon: '☣️',
        cost: 450,
        x: 880,
        y: 80,
        connections: ['cat_acid_pool', 'cat_furball_frenzy'],
        description: 'KEYSTONE: Spews a nonstop stream of toxic bio-hairballs, melting hordes and bosses into green sludge.',
        element: ElementType.CHONK_FORTRESS
      },

      // --- BUILD C: NINE LIVES & IMMORTAL FLUFF (Bottom) ---
      cat_def_minor: {
        id: 'cat_def_minor',
        name: 'Iron Whiskers (หนวดเหล็กกล้า)',
        type: 'minor',
        classType: PlayerClass.CAT_TANK,
        icon: '🐱',
        cost: 100,
        x: 430,
        y: 440,
        connections: ['cat_root', 'cattank_nine_lives', 'cat_taunt_minor'],
        description: '+20 Max HP and +1 Flat Defense.',
        stats: { maxHp: 20, defense: 1 }
      },
      cat_taunt_minor: {
        id: 'cat_taunt_minor',
        name: 'Feline Hiss (เสียงขู่ฟ่อ)',
        type: 'minor',
        classType: PlayerClass.CAT_TANK,
        icon: '😾',
        cost: 100,
        x: 570,
        y: 440,
        connections: ['cat_root', 'cattank_aggro_taunt', 'cat_def_minor'],
        description: '+15% Move Speed and draws monster aggression away from friends.',
        stats: { moveSpeed: 1 }
      },
      cattank_nine_lives: {
        id: 'cattank_nine_lives',
        name: 'Nine Lives Aegis (พรแห่ง 9 ชีวิต)',
        type: 'notable',
        classType: PlayerClass.CAT_TANK,
        icon: '✨',
        cost: 360,
        x: 360,
        y: 520,
        connections: ['cat_def_minor', 'cat_immortal_purr', 'cat_colossus'],
        description: 'NOTABLE: Grants a protective spirit shield that absorbs fatal blows and regenerates every 30s.',
        signatureSkillId: 'cattank_nine_lives',
        stats: { maxHp: 30, defense: 2 }
      },
      cattank_aggro_taunt: {
        id: 'cattank_aggro_taunt',
        name: 'Royal Cat Taunt (เสียงคำรามเจ้าเหมียว)',
        type: 'notable',
        classType: PlayerClass.CAT_TANK,
        icon: '👑',
        cost: 360,
        x: 640,
        y: 520,
        connections: ['cat_taunt_minor', 'cat_zoomies', 'cat_colossus'],
        description: 'NOTABLE: Forces nearby monsters to focus on the Cat Tank, raising defense by +3 while taunting.',
        signatureSkillId: 'cattank_aggro_taunt',
        stats: { defense: 3 }
      },
      cat_immortal_purr: {
        id: 'cat_immortal_purr',
        name: 'Healing Purr (เสียงกรนฟื้นฟู)',
        type: 'minor',
        classType: PlayerClass.CAT_TANK,
        icon: '❤️',
        cost: 150,
        x: 300,
        y: 600,
        connections: ['cattank_nine_lives', 'cat_colossus'],
        description: 'Regenerates 2 HP per second for self and nearby teammates.',
        stats: { maxHp: 25 }
      },
      cat_zoomies: {
        id: 'cat_zoomies',
        name: 'Midnight Zoomies (วิ่งพล่านกลางดึก)',
        type: 'minor',
        classType: PlayerClass.CAT_TANK,
        icon: '💨',
        cost: 150,
        x: 700,
        y: 600,
        connections: ['cattank_aggro_taunt', 'cat_colossus'],
        description: '+20% Move Speed and monsters crossing path take bump damage.',
        stats: { moveSpeed: 2 }
      },
      cat_colossus: {
        id: 'cat_colossus',
        name: 'Immortal Feline Colossus (จักรพรรดิเหมียวอมตะ)',
        type: 'keystone',
        classType: PlayerClass.CAT_TANK,
        icon: '👑',
        cost: 450,
        x: 500,
        y: 630,
        connections: ['cattank_nine_lives', 'cattank_aggro_taunt', 'cat_immortal_purr', 'cat_zoomies'],
        description: 'KEYSTONE: Becomes an unkillable behemoth with +80 Max HP, +5 Defense, and pulse-waves that heal teammates when taking damage.',
        stats: { maxHp: 80, defense: 5 }
      }
    }
  },

  [PlayerClass.COWBOY]: {
    classType: PlayerClass.COWBOY,
    title: 'The Desperado — Twin Peacemaker Mastery Web',
    elementTitle: '🤠 Twin Peacemaker Lead & Barbed Lasso',
    rootId: 'cow_root',
    nodes: {
      cow_root: {
        id: 'cow_root',
        name: 'Frontier Saloon (บาร์คาวบอยชายแดน)',
        type: 'root',
        classType: PlayerClass.COWBOY,
        icon: '🤠',
        cost: 0,
        x: 500,
        y: 350,
        connections: ['cow_draw_minor', 'cow_lasso_minor', 'cow_bounty_minor', 'cow_dodge_minor'],
        description: 'Dusty frontier saloon of the Desperado. Starting origin root.',
        stats: { moveSpeed: 1, maxHp: 10 }
      },

      // --- BUILD A: FAST DRAW & RICOCHET (Top-Left) ---
      cow_draw_minor: {
        id: 'cow_draw_minor',
        name: 'Hair Trigger (ไกปืนเบาพิเศษ)',
        type: 'minor',
        classType: PlayerClass.COWBOY,
        icon: '🔫',
        cost: 95,
        x: 390,
        y: 260,
        connections: ['cow_root', 'cowboy_quick_draw', 'cow_lead_minor'],
        description: '+10% Attack Speed and +8 Flat Damage for revolvers.',
        stats: { damageBonus: 1 }
      },
      cow_lead_minor: {
        id: 'cow_lead_minor',
        name: 'Hollow-Point Lead (กระสุนหัวรู)',
        type: 'minor',
        classType: PlayerClass.COWBOY,
        icon: '🎯',
        cost: 110,
        x: 290,
        y: 280,
        connections: ['cow_draw_minor', 'cow_fan_hammer', 'cow_ricochet_1'],
        description: 'Bullets deal bleed wounds for 3s and pierce +1 monster.',
        stats: { damageBonus: 1 }
      },
      cowboy_quick_draw: {
        id: 'cowboy_quick_draw',
        name: 'Twin Peacemakers (ปืนลูกโม่คู่)',
        type: 'notable',
        classType: PlayerClass.COWBOY,
        icon: '⚡',
        cost: 360,
        x: 300,
        y: 190,
        connections: ['cow_draw_minor', 'cow_ricochet_1'],
        description: 'NOTABLE: Dual wields twin revolvers, firing double shots simultaneously in an ultra-fast volley.',
        signatureSkillId: 'cowboy_quick_draw',
        element: ElementType.DEADEYE_PIERCE
      },
      cow_ricochet_1: {
        id: 'cow_ricochet_1',
        name: 'Copper Ricochet (กระสุนชิ่ง)',
        type: 'minor',
        classType: PlayerClass.COWBOY,
        icon: '💫',
        cost: 135,
        x: 210,
        y: 130,
        connections: ['cowboy_quick_draw', 'cow_lead_minor', 'cow_deadeye'],
        description: 'Bullets ricochet toward nearest enemy upon hit.',
        stats: { damageBonus: 2 }
      },
      cow_fan_hammer: {
        id: 'cow_fan_hammer',
        name: 'Fan the Hammer (สับนกปืนรัว)',
        type: 'notable',
        classType: PlayerClass.COWBOY,
        icon: '💥',
        cost: 380,
        x: 200,
        y: 230,
        connections: ['cow_lead_minor', 'cow_deadeye'],
        description: 'NOTABLE: Every 5th attack fires a 6-shot rapid fan in a wide cone.',
        stats: { damageBonus: 2 }
      },
      cow_deadeye: {
        id: 'cow_deadeye',
        name: 'High Noon Dead Eye (ตาทิพย์เที่ยงตรง)',
        type: 'keystone',
        classType: PlayerClass.COWBOY,
        icon: '👁️',
        cost: 450,
        x: 120,
        y: 80,
        connections: ['cow_ricochet_1', 'cow_fan_hammer'],
        description: 'KEYSTONE: Critical hit chance increased by +25% with 2.5x critical damage multiplier and guaranteed ricochets.',
        element: ElementType.DEADEYE_PIERCE
      },

      // --- BUILD B: BARBED LASSO & RODEO (Top-Right) ---
      cow_lasso_minor: {
        id: 'cow_lasso_minor',
        name: 'Braided Rawhide (บ่วงเชือกหนังถัก)',
        type: 'minor',
        classType: PlayerClass.COWBOY,
        icon: '🪢',
        cost: 95,
        x: 610,
        y: 260,
        connections: ['cow_root', 'cowboy_lasso_upgrade', 'cow_snare_minor'],
        description: '+15% Lasso range and ensnares for +1.0s longer.',
        stats: { damageBonus: 1 }
      },
      cow_snare_minor: {
        id: 'cow_snare_minor',
        name: 'Barbed Wire (ขดลวดหนาม)',
        type: 'minor',
        classType: PlayerClass.COWBOY,
        icon: '🩸',
        cost: 110,
        x: 710,
        y: 280,
        connections: ['cow_lasso_minor', 'cow_hogtie', 'cow_barbed_ring'],
        description: 'Ensnared enemies take +20% damage from all party members.',
        stats: { damageBonus: 1 }
      },
      cowboy_lasso_upgrade: {
        id: 'cowboy_lasso_upgrade',
        name: 'Ensnaring Lasso (บ่วงบาศก์ตรึงวิญญาณ)',
        type: 'notable',
        classType: PlayerClass.COWBOY,
        icon: '➰',
        cost: 360,
        x: 700,
        y: 190,
        connections: ['cow_lasso_minor', 'cow_barbed_ring'],
        description: 'NOTABLE: Hurls braided lasso rings that bind, pull, and crush clusters of monsters.',
        signatureSkillId: 'cowboy_lasso_upgrade',
        element: ElementType.DEADEYE_PIERCE
      },
      cow_barbed_ring: {
        id: 'cow_barbed_ring',
        name: 'Barbed Whirl (วงล้อลวดหนาม)',
        type: 'minor',
        classType: PlayerClass.COWBOY,
        icon: '⚙️',
        cost: 135,
        x: 790,
        y: 130,
        connections: ['cowboy_lasso_upgrade', 'cow_snare_minor', 'cow_rodeo_king'],
        description: '+15 Flat Damage and lasso expands into a razor ring.',
        stats: { damageBonus: 2 }
      },
      cow_hogtie: {
        id: 'cow_hogtie',
        name: 'Hogtie Stun (มัดตรึงล่ามโซ่)',
        type: 'notable',
        classType: PlayerClass.COWBOY,
        icon: '⛓️',
        cost: 380,
        x: 800,
        y: 230,
        connections: ['cow_snare_minor', 'cow_rodeo_king'],
        description: 'NOTABLE: Lasso pulls elite monsters and bosses, disabling them for 2.5s.',
        stats: { damageBonus: 2 }
      },
      cow_rodeo_king: {
        id: 'cow_rodeo_king',
        name: 'Rodeo Dominator (ราชันโรเดโอ)',
        type: 'keystone',
        classType: PlayerClass.COWBOY,
        icon: '🐂',
        cost: 450,
        x: 880,
        y: 80,
        connections: ['cow_barbed_ring', 'cow_hogtie'],
        description: 'KEYSTONE: Lasso pulls in dozens of monsters into a compact vortex and detonates with a colossal dynamite blast.',
        element: ElementType.DEADEYE_PIERCE
      },

      // --- BUILD C: BOUNTY HUNTER & OUTLAW MOBILITY (Bottom) ---
      cow_bounty_minor: {
        id: 'cow_bounty_minor',
        name: 'Bounty Hunter Badge (ตรานายอำเภอ)',
        type: 'minor',
        classType: PlayerClass.COWBOY,
        icon: '⭐',
        cost: 100,
        x: 430,
        y: 440,
        connections: ['cow_root', 'cowboy_hollow_point', 'cow_dodge_minor'],
        description: 'Killing marked monsters grants +20% bonus EXP and +10% move speed.',
        stats: { moveSpeed: 1 }
      },
      cow_dodge_minor: {
        id: 'cow_dodge_minor',
        name: 'Spur Boots (รองเท้าติดเดือย)',
        type: 'minor',
        classType: PlayerClass.COWBOY,
        icon: '👢',
        cost: 100,
        x: 570,
        y: 440,
        connections: ['cow_root', 'cowboy_tumble', 'cow_bounty_minor'],
        description: '+15% Move Speed and +10 Max HP.',
        stats: { moveSpeed: 1, maxHp: 10 }
      },
      cowboy_hollow_point: {
        id: 'cowboy_hollow_point',
        name: 'Bounty Mark (หมายจับล่าหัว)',
        type: 'notable',
        classType: PlayerClass.COWBOY,
        icon: '📜',
        cost: 360,
        x: 360,
        y: 520,
        connections: ['cow_bounty_minor', 'cow_gold_pouch', 'cow_legend_west'],
        description: 'NOTABLE: Marks elite monsters with bounties. Slain bounties drop gold and boost party damage.',
        signatureSkillId: 'cowboy_hollow_point',
        stats: { damageBonus: 2 }
      },
      cowboy_tumble: {
        id: 'cowboy_tumble',
        name: 'Gunslinger Tumble (ม้วนตัวหลบกระสุน)',
        type: 'notable',
        classType: PlayerClass.COWBOY,
        icon: '💨',
        cost: 360,
        x: 640,
        y: 520,
        connections: ['cow_dodge_minor', 'cow_gunslinger_stride', 'cow_legend_west'],
        description: 'NOTABLE: Dashing leaves gunpowder smoke that blinds enemies and reloads weapons instantly.',
        signatureSkillId: 'cowboy_tumble',
        stats: { moveSpeed: 2 }
      },
      cow_gold_pouch: {
        id: 'cow_gold_pouch',
        name: 'Outlaw Gold Bag (ถุงทองนอกกฎหมาย)',
        type: 'minor',
        classType: PlayerClass.COWBOY,
        icon: '💰',
        cost: 150,
        x: 300,
        y: 600,
        connections: ['cowboy_hollow_point', 'cow_legend_west'],
        description: '+25% Item and gold pickup radius with +15 Max HP.',
        stats: { pickupRadius: 2, maxHp: 15 }
      },
      cow_gunslinger_stride: {
        id: 'cow_gunslinger_stride',
        name: 'Desert Drifter (ผู้พเนจรทะเลทราย)',
        type: 'minor',
        classType: PlayerClass.COWBOY,
        icon: '🏜️',
        cost: 150,
        x: 700,
        y: 600,
        connections: ['cowboy_tumble', 'cow_legend_west'],
        description: '+15% Move Speed and +1 Flat Defense.',
        stats: { moveSpeed: 1, defense: 1 }
      },
      cow_legend_west: {
        id: 'cow_legend_west',
        name: 'Legend of the West (ตำนานแดนเถื่อน)',
        type: 'keystone',
        classType: PlayerClass.COWBOY,
        icon: '🏆',
        cost: 450,
        x: 500,
        y: 630,
        connections: ['cowboy_hollow_point', 'cowboy_tumble', 'cow_gold_pouch', 'cow_gunslinger_stride'],
        description: 'KEYSTONE: Grants permanent +20% Move Speed, +30% All Damage, and makes all bullet shots pierce 3 monsters.',
        stats: { moveSpeed: 2, damageBonus: 3 }
      }
    }
  },

  [PlayerClass.CELESTIAL_MECHA]: {
    classType: PlayerClass.CELESTIAL_MECHA,
    title: 'The GN Vanguard — Orbital Plasma Mastery Web',
    elementTitle: '🤖 Celestial Plasma & Full-Burst Lasers',
    rootId: 'mecha_root',
    nodes: {
      mecha_root: {
        id: 'mecha_root',
        name: 'Orbital Hangar (โรงเก็บยานอวกาศ)',
        type: 'root',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '🤖',
        cost: 0,
        x: 500,
        y: 350,
        connections: ['mecha_drive_minor', 'mecha_cannon_minor', 'mecha_shield_minor', 'mecha_thruster_minor'],
        description: 'Orbital launchpad of the Celestial Mecha. Starting origin root.',
        stats: { defense: 1, moveSpeed: 1 }
      },

      // --- BUILD A: GN BEAM SABER & TRANS-AM (Top-Left) ---
      mecha_drive_minor: {
        id: 'mecha_drive_minor',
        name: 'GN Drive Core (เตาปฏิกรณ์ GN)',
        type: 'minor',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '⚡',
        cost: 95,
        x: 390,
        y: 260,
        connections: ['mecha_root', 'mecha_saber_overdrive', 'mecha_flow_minor'],
        description: '+12 Flat Damage and +15% Melee Saber Cleave Area.',
        stats: { damageBonus: 1 }
      },
      mecha_flow_minor: {
        id: 'mecha_flow_minor',
        name: 'Plasma Conduit (ท่อส่งพลาสมา)',
        type: 'minor',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '🔷',
        cost: 110,
        x: 290,
        y: 280,
        connections: ['mecha_drive_minor', 'mecha_twin_cleave', 'mecha_plasma_edge'],
        description: 'Beam sabers inflict Shock status dealing ticking plasma arc damage.',
        stats: { damageBonus: 1 }
      },
      mecha_saber_overdrive: {
        id: 'mecha_saber_overdrive',
        name: 'GN Saber Overdrive (เร่งพลังดาบแสง)',
        type: 'notable',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '⚔️',
        cost: 360,
        x: 300,
        y: 190,
        connections: ['mecha_drive_minor', 'mecha_plasma_edge'],
        description: 'NOTABLE: Supercharges dual beam sabers with +30% cleave area and high-frequency plasma vibration.',
        signatureSkillId: 'mecha_saber_overdrive',
        element: ElementType.CELESTIAL_PLASMA
      },
      mecha_plasma_edge: {
        id: 'mecha_plasma_edge',
        name: 'Thermal Edge (คมมีดความร้อนสูง)',
        type: 'minor',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '💠',
        cost: 135,
        x: 210,
        y: 130,
        connections: ['mecha_saber_overdrive', 'mecha_flow_minor', 'mecha_trans_am'],
        description: '+15 Flat Damage and +10% Attack Speed for beam sabers.',
        stats: { damageBonus: 2 }
      },
      mecha_twin_cleave: {
        id: 'mecha_twin_cleave',
        name: 'Dual Saber X-Slash (ท่าฟันดาบคู่กากบาท)',
        type: 'notable',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '✖️',
        cost: 380,
        x: 200,
        y: 230,
        connections: ['mecha_flow_minor', 'mecha_trans_am'],
        description: 'NOTABLE: Every 4th saber swing unleashes an energetic cross-cleave striking 360 degrees.',
        element: ElementType.CELESTIAL_PLASMA
      },
      mecha_trans_am: {
        id: 'mecha_trans_am',
        name: 'Trans-Am Omnislash (ทรานซัมฟันไร้เงา)',
        type: 'keystone',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '🌟',
        cost: 450,
        x: 120,
        y: 80,
        connections: ['mecha_plasma_edge', 'mecha_twin_cleave'],
        description: 'KEYSTONE: Overclocks GN Drive into Trans-Am mode, boosting move speed by +30%, attack speed by +40%, and turning saber swings into screen-wide plasma waves.',
        element: ElementType.CELESTIAL_PLASMA
      },

      // --- BUILD B: FULL BURST WING CANNONS (Top-Right) ---
      mecha_cannon_minor: {
        id: 'mecha_cannon_minor',
        name: 'Capacitor Banks (แบตเตอรี่พลาสมา)',
        type: 'minor',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '🔋',
        cost: 95,
        x: 610,
        y: 260,
        connections: ['mecha_root', 'mecha_laser_salvo', 'mecha_lens_minor'],
        description: '+1 Wing Laser projectile count and +10% Laser Speed.',
        stats: { damageBonus: 1 }
      },
      mecha_lens_minor: {
        id: 'mecha_lens_minor',
        name: 'Focusing Crystals (คริสตัลรวมแสง)',
        type: 'minor',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '💎',
        cost: 110,
        x: 710,
        y: 280,
        connections: ['mecha_cannon_minor', 'mecha_hyper_beam', 'mecha_array_1'],
        description: 'Lasers pierce +2 additional monsters with bright plasma combustion.',
        stats: { damageBonus: 1 }
      },
      mecha_laser_salvo: {
        id: 'mecha_laser_salvo',
        name: 'Wing Laser Salvo (ระดมยิงปีกเลเซอร์)',
        type: 'notable',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '✨',
        cost: 360,
        x: 700,
        y: 190,
        connections: ['mecha_cannon_minor', 'mecha_array_1'],
        description: 'NOTABLE: Fires high-velocity plasma wing beams that track and eradicate approaching foes.',
        signatureSkillId: 'mecha_laser_salvo',
        element: ElementType.CELESTIAL_PLASMA
      },
      mecha_array_1: {
        id: 'mecha_array_1',
        name: 'Collimator Array (แถบกระจายลำแสง)',
        type: 'minor',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '🔭',
        cost: 135,
        x: 790,
        y: 130,
        connections: ['mecha_laser_salvo', 'mecha_lens_minor', 'mecha_full_burst'],
        description: '+15 Flat Damage and +1 additional laser beam in each salvo.',
        stats: { damageBonus: 2 }
      },
      mecha_hyper_beam: {
        id: 'mecha_hyper_beam',
        name: 'Hyper Mega Launcher (ปืนใหญ่ไฮเปอร์เมก้า)',
        type: 'notable',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '📡',
        cost: 380,
        x: 800,
        y: 230,
        connections: ['mecha_lens_minor', 'mecha_full_burst'],
        description: 'NOTABLE: Periodically charges and fires a colossal piercing particle cannon beam across the entire screen.',
        element: ElementType.CELESTIAL_PLASMA
      },
      mecha_full_burst: {
        id: 'mecha_full_burst',
        name: 'Full Burst Calamity (ฟูลเบิร์สทำลายล้าง)',
        type: 'keystone',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '🎆',
        cost: 450,
        x: 880,
        y: 80,
        connections: ['mecha_array_1', 'mecha_hyper_beam'],
        description: 'KEYSTONE: Unleashes all orbital wing cannons and laser funnels at once, incinerating entire legions in radiant cyan firestorms.',
        element: ElementType.CELESTIAL_PLASMA
      },

      // --- BUILD C: GN BARRIER & AFTERBURNER HOVER (Bottom) ---
      mecha_shield_minor: {
        id: 'mecha_shield_minor',
        name: 'Particle Coating (เคลือบผิวอนุภาค)',
        type: 'minor',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '🛡️',
        cost: 100,
        x: 430,
        y: 440,
        connections: ['mecha_root', 'mecha_gn_barrier', 'mecha_thruster_minor'],
        description: '+20 Max HP and +1 Flat Defense.',
        stats: { maxHp: 20, defense: 1 }
      },
      mecha_thruster_minor: {
        id: 'mecha_thruster_minor',
        name: 'Ion Verniers (ไอออนเวอร์เนียร์)',
        type: 'minor',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '🚀',
        cost: 100,
        x: 570,
        y: 440,
        connections: ['mecha_root', 'mecha_thruster', 'mecha_shield_minor'],
        description: '+12% Move Speed and enables smooth hover drifting.',
        stats: { moveSpeed: 1 }
      },
      mecha_gn_barrier: {
        id: 'mecha_gn_barrier',
        name: 'GN Forcefield (บาเรียสนามพลัง GN)',
        type: 'notable',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '🌐',
        cost: 360,
        x: 360,
        y: 520,
        connections: ['mecha_shield_minor', 'mecha_fortress', 'mecha_gundam_core'],
        description: 'NOTABLE: Projects an energy forcefield that absorbs incoming projectile damage and reflects back shock charges.',
        signatureSkillId: 'mecha_gn_barrier',
        stats: { defense: 2, maxHp: 20 }
      },
      mecha_thruster: {
        id: 'mecha_thruster',
        name: 'Afterburner Boosters (ไอพ่นขับดัน)',
        type: 'notable',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '💨',
        cost: 360,
        x: 640,
        y: 520,
        connections: ['mecha_thruster_minor', 'mecha_warp_dash', 'mecha_gundam_core'],
        description: 'NOTABLE: High-output thrusters increase base movement speed by +20% with permanent hover flight.',
        signatureSkillId: 'mecha_thruster',
        stats: { moveSpeed: 2 }
      },
      mecha_fortress: {
        id: 'mecha_fortress',
        name: 'Plasma Aegis (โล่พลาสมาบริสุทธิ์)',
        type: 'minor',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '🔰',
        cost: 150,
        x: 300,
        y: 600,
        connections: ['mecha_gn_barrier', 'mecha_gundam_core'],
        description: '+30 Max HP and +2 Flat Defense.',
        stats: { maxHp: 30, defense: 2 }
      },
      mecha_warp_dash: {
        id: 'mecha_warp_dash',
        name: 'Quantum Warp Dash (พุ่งวาร์ปควอนตัม)',
        type: 'minor',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '🌌',
        cost: 150,
        x: 700,
        y: 600,
        connections: ['mecha_thruster', 'mecha_gundam_core'],
        description: 'Dash distance increased by +35% with complete invulnerability during dash.',
        stats: { moveSpeed: 1 }
      },
      mecha_gundam_core: {
        id: 'mecha_gundam_core',
        name: 'Celestial Dominator (จ้าวแห่งอวกาศขั้นสูงสุด)',
        type: 'keystone',
        classType: PlayerClass.CELESTIAL_MECHA,
        icon: '👑',
        cost: 450,
        x: 500,
        y: 630,
        connections: ['mecha_gn_barrier', 'mecha_thruster', 'mecha_fortress', 'mecha_warp_dash'],
        description: 'KEYSTONE: Unleashes full celestial protocol: +60 Max HP, +3 Defense, +20% Move Speed, and auto-discharges orbital lightning strikes at all nearby enemies.',
        stats: { maxHp: 60, defense: 3, moveSpeed: 2 }
      }
    }
  },

  [PlayerClass.GAMBLER]: {
    classType: PlayerClass.GAMBLER,
    title: 'The High Roller — Fortune Deck Mastery Web',
    elementTitle: '🃏 Lucky Arcane Cards & 777 Jackpot',
    rootId: 'gam_root',
    nodes: {
      gam_root: {
        id: 'gam_root',
        name: 'Golden Casino Core (คาสิโนทองคำ)',
        type: 'root',
        classType: PlayerClass.GAMBLER,
        icon: '🃏',
        cost: 0,
        x: 500,
        y: 350,
        connections: ['gam_card_minor', 'gam_dice_minor', 'gam_greed_minor', 'gam_luck_minor'],
        description: 'The glittering VIP suite of the High Roller. Starting origin root.',
        stats: { damageBonus: 1, moveSpeed: 1 }
      },

      // --- BUILD A: CARD FAN & ROYAL FLUSH (Top-Left) ---
      gam_card_minor: {
        id: 'gam_card_minor',
        name: 'Razor Card Edge (ขอบไพ่คมกริบ)',
        type: 'minor',
        classType: PlayerClass.GAMBLER,
        icon: '🎴',
        cost: 95,
        x: 390,
        y: 260,
        connections: ['gam_root', 'gambler_royal_flush', 'gam_spread_minor'],
        description: '+8 Flat Damage and +10% Card flight speed.',
        stats: { damageBonus: 1 }
      },
      gam_spread_minor: {
        id: 'gam_spread_minor',
        name: 'Card Fan Spread (กรีดไพ่รูปพัด)',
        type: 'minor',
        classType: PlayerClass.GAMBLER,
        icon: '👐',
        cost: 110,
        x: 290,
        y: 280,
        connections: ['gam_card_minor', 'gam_wild_joker', 'gam_ace_spades'],
        description: 'Throws +1 additional playing card per fan attack.',
        stats: { damageBonus: 1 }
      },
      gambler_royal_flush: {
        id: 'gambler_royal_flush',
        name: 'Royal Flush Cascade (ไพ่รอยัลฟลัช)',
        type: 'notable',
        classType: PlayerClass.GAMBLER,
        icon: '👑',
        cost: 360,
        x: 300,
        y: 190,
        connections: ['gam_card_minor', 'gam_ace_spades'],
        description: 'NOTABLE: Flings an expanded fan of razor tarot cards with piercing and fire ignite ticks.',
        signatureSkillId: 'gambler_royal_flush',
        element: ElementType.LUCKY_ARCANE
      },
      gam_ace_spades: {
        id: 'gam_ace_spades',
        name: 'Ace of Spades (เอซโพดำมรณะ)',
        type: 'minor',
        classType: PlayerClass.GAMBLER,
        icon: '♠️',
        cost: 135,
        x: 210,
        y: 130,
        connections: ['gambler_royal_flush', 'gam_spread_minor', 'gam_royal_cascade'],
        description: '+15 Flat Damage and critical hits trigger explosive card shards.',
        stats: { damageBonus: 2 }
      },
      gam_wild_joker: {
        id: 'gam_wild_joker',
        name: 'Wild Joker Shuffle (ไพ่โจ๊กเกอร์หลอน)',
        type: 'notable',
        classType: PlayerClass.GAMBLER,
        icon: '🤡',
        cost: 380,
        x: 200,
        y: 230,
        connections: ['gam_spread_minor', 'gam_royal_cascade'],
        description: 'NOTABLE: Random chance to throw a giant homing Joker card dealing 3x damage.',
        element: ElementType.LUCKY_ARCANE
      },
      gam_royal_cascade: {
        id: 'gam_royal_cascade',
        name: 'Dealer of Destiny (จอมบงการชะตา)',
        type: 'keystone',
        classType: PlayerClass.GAMBLER,
        icon: '🂠',
        cost: 450,
        x: 120,
        y: 80,
        connections: ['gam_ace_spades', 'gam_wild_joker'],
        description: 'KEYSTONE: Continuous stream of 7 cards flying in a 360-degree cyclone shredding all nearby hordes.',
        element: ElementType.LUCKY_ARCANE
      },

      // --- BUILD B: LUCKY DICE & 777 JACKPOT (Top-Right) ---
      gam_dice_minor: {
        id: 'gam_dice_minor',
        name: 'Weighted Die (ลูกเต๋าถ่วงน้ำหนัก)',
        type: 'minor',
        classType: PlayerClass.GAMBLER,
        icon: '🎲',
        cost: 95,
        x: 610,
        y: 260,
        connections: ['gam_root', 'gambler_loaded_dice', 'gam_high_roller_crit'],
        description: '+10% Critical Chance and raises minimum dice roll to 2.',
        stats: { damageBonus: 1 }
      },
      gam_high_roller_crit: {
        id: 'gam_high_roller_crit',
        name: 'Critical Streak (สตรีคคริติคอล)',
        type: 'minor',
        classType: PlayerClass.GAMBLER,
        icon: '🎯',
        cost: 110,
        x: 710,
        y: 280,
        connections: ['gam_dice_minor', 'gam_golden_roll', 'gambler_jackpot'],
        description: 'Consecutive critical hits increase critical damage by +15% (stacks 4 times).',
        stats: { damageBonus: 1 }
      },
      gambler_loaded_dice: {
        id: 'gambler_loaded_dice',
        name: 'Loaded Dice Throw (ทอยเต๋านำโชค)',
        type: 'notable',
        classType: PlayerClass.GAMBLER,
        icon: '🎲',
        cost: 360,
        x: 700,
        y: 190,
        connections: ['gam_dice_minor', 'gam_golden_roll'],
        description: 'NOTABLE: Tosses explosive lucky dice that bounce and detonate. Rolling a 6 triggers a golden jackpot blast!',
        signatureSkillId: 'gambler_loaded_dice',
        element: ElementType.LUCKY_ARCANE
      },
      gam_golden_roll: {
        id: 'gam_golden_roll',
        name: 'Golden Sixes (เต๋าหกนำโชค)',
        type: 'minor',
        classType: PlayerClass.GAMBLER,
        icon: '✨',
        cost: 135,
        x: 790,
        y: 130,
        connections: ['gambler_loaded_dice', 'gam_high_roller_crit', 'gambler_jackpot'],
        description: 'Increases the chance of rolling 5 and 6 by +25% with larger blast radius.',
        stats: { damageBonus: 2 }
      },
      gambler_jackpot: {
        id: 'gambler_jackpot',
        name: 'Jackpot 777 Frenzy (แจ็กพอตแตก 777)',
        type: 'keystone',
        classType: PlayerClass.GAMBLER,
        icon: '🎰',
        cost: 450,
        x: 880,
        y: 80,
        connections: ['gam_golden_roll', 'gam_high_roller_crit'],
        description: 'KEYSTONE: Periodically triggers 777 slot jackpot fireworks, raining coins and blasting all nearby foes in a massive explosion.',
        signatureSkillId: 'gambler_jackpot',
        element: ElementType.LUCKY_ARCANE
      },

      // --- BUILD C: CASINO GREED & HIGH ROLLER (Bottom) ---
      gam_greed_minor: {
        id: 'gam_greed_minor',
        name: 'Golden Ante (ชิปเดิมพันทองคำ)',
        type: 'minor',
        classType: PlayerClass.GAMBLER,
        icon: '🪙',
        cost: 100,
        x: 430,
        y: 440,
        connections: ['gam_root', 'gambler_fortune_greed', 'gam_luck_minor'],
        description: '+15 Max HP and gold coins picked up grant +5% speed for 4s.',
        stats: { maxHp: 15 }
      },
      gam_luck_minor: {
        id: 'gam_luck_minor',
        name: 'Lady Luck Favor (พรแห่งเทพีนำโชค)',
        type: 'minor',
        classType: PlayerClass.GAMBLER,
        icon: '🍀',
        cost: 100,
        x: 570,
        y: 440,
        connections: ['gam_root', 'gam_coin_storm', 'gam_greed_minor'],
        description: '+10% Move Speed and +20% Item Pickup Range.',
        stats: { moveSpeed: 1, pickupRadius: 1 }
      },
      gambler_fortune_greed: {
        id: 'gambler_fortune_greed',
        name: 'High Roller Magnetism (แม่เหล็กนักเสี่ยงโชค)',
        type: 'notable',
        classType: PlayerClass.GAMBLER,
        icon: '🧲',
        cost: 360,
        x: 360,
        y: 520,
        connections: ['gam_greed_minor', 'gam_vault_ante', 'gam_casino_king'],
        description: 'NOTABLE: Card hits have a chance to extract gold coins from monsters and vacuum them instantly.',
        signatureSkillId: 'gambler_fortune_greed',
        stats: { pickupRadius: 2 }
      },
      gam_coin_storm: {
        id: 'gam_coin_storm',
        name: 'Golden Shrapnel (สะเก็ดเหรียญทอง)',
        type: 'notable',
        classType: PlayerClass.GAMBLER,
        icon: '💰',
        cost: 360,
        x: 640,
        y: 520,
        connections: ['gam_luck_minor', 'gam_all_in', 'gam_casino_king'],
        description: 'NOTABLE: Picking up gold coins releases ricocheting gold sparks that damage nearby enemies.',
        stats: { damageBonus: 2 }
      },
      gam_vault_ante: {
        id: 'gam_vault_ante',
        name: 'Vault Insurance (ประกันภัยคาสิโน)',
        type: 'minor',
        classType: PlayerClass.GAMBLER,
        icon: '🏦',
        cost: 150,
        x: 300,
        y: 600,
        connections: ['gambler_fortune_greed', 'gam_casino_king'],
        description: '+25 Max HP and taking heavy damage scatters coins that heal upon pickup.',
        stats: { maxHp: 25 }
      },
      gam_all_in: {
        id: 'gam_all_in',
        name: 'Double or Nothing (สองเท่าหรือศูนย์)',
        type: 'minor',
        classType: PlayerClass.GAMBLER,
        icon: '⚖️',
        cost: 150,
        x: 700,
        y: 600,
        connections: ['gam_coin_storm', 'gam_casino_king'],
        description: '+15% Move Speed and +15% Damage Bonus.',
        stats: { moveSpeed: 1, damageBonus: 2 }
      },
      gam_casino_king: {
        id: 'gam_casino_king',
        name: 'Vegas Casino King (ราชาแห่งเวกัส)',
        type: 'keystone',
        classType: PlayerClass.GAMBLER,
        icon: '👑',
        cost: 450,
        x: 500,
        y: 630,
        connections: ['gambler_fortune_greed', 'gam_coin_storm', 'gam_vault_ante', 'gam_all_in'],
        description: 'KEYSTONE: The ultimate gambler: +50 Max HP, +25% Move Speed, +30% All Damage, and permanent slot coin storms swirling around you.',
        stats: { maxHp: 50, moveSpeed: 2, damageBonus: 3 }
      }
    }
  },

  ['universal']: {
    classType: 'universal',
    title: 'Universal Ancient Roots — Soul Ascension Web',
    elementTitle: '🌌 Cosmic Soul & EXP Attunement',
    rootId: 'uni_root',
    nodes: {
      uni_root: {
        id: 'uni_root',
        name: 'Ancestral Soul Core (แก่นวิญญาณบรรพกาล)',
        type: 'root',
        classType: 'universal',
        icon: '🌌',
        cost: 0,
        x: 500,
        y: 500,
        connections: ['uni_exp_1', 'uni_exp_branch_left', 'uni_exp_branch_right'],
        description: 'The ancient cosmic origin tree shared by all classes. Starting origin root.',
        stats: { maxHp: 10 }
      },

      // --- Central EXP Trunk ---
      uni_exp_1: {
        id: 'uni_exp_1',
        name: 'Soul Attunement I (ดูดซับวิญญาณ 1)',
        type: 'minor',
        classType: 'universal',
        icon: '📜',
        cost: 45,
        x: 500,
        y: 410,
        connections: ['uni_root', 'uni_exp_2'],
        description: '+10% Permanent EXP Multiplier for all hero classes.',
        stats: { expMultiplier: 10 }
      },
      uni_exp_2: {
        id: 'uni_exp_2',
        name: 'Soul Attunement II (ดูดซับวิญญาณ 2)',
        type: 'minor',
        classType: 'universal',
        icon: '📖',
        cost: 95,
        x: 500,
        y: 320,
        connections: ['uni_exp_1', 'uni_exp_3'],
        description: '+10% Permanent EXP Multiplier (+20% Total).',
        stats: { expMultiplier: 10 }
      },
      uni_exp_3: {
        id: 'uni_exp_3',
        name: 'Wisdom of the Elders (ปรีชาญาณโบราณ)',
        type: 'notable',
        classType: 'universal',
        icon: '✨',
        cost: 175,
        x: 500,
        y: 230,
        connections: ['uni_exp_2', 'uni_exp_4'],
        description: 'NOTABLE: +10% Permanent EXP Multiplier (+30% Total) & +25% Soul Gem Pickup Radius.',
        stats: { expMultiplier: 10, pickupRadius: 1 }
      },
      uni_exp_4: {
        id: 'uni_exp_4',
        name: 'Transcendental Focus (สมาธิรู้แจ้ง)',
        type: 'notable',
        classType: 'universal',
        icon: '🔮',
        cost: 280,
        x: 500,
        y: 150,
        connections: ['uni_exp_3', 'uni_keystone_mastery'],
        description: 'NOTABLE: +10% Permanent EXP Multiplier (+40% Total) & +20 Max HP.',
        stats: { expMultiplier: 10, maxHp: 20 }
      },
      uni_keystone_mastery: {
        id: 'uni_keystone_mastery',
        name: 'Ascendant Enlightenment (การรู้แจ้งอันสมบูรณ์)',
        type: 'keystone',
        classType: 'universal',
        icon: '👑',
        cost: 450,
        x: 500,
        y: 70,
        connections: ['uni_exp_4'],
        description: 'ASCENSION KEYSTONE: +10% Permanent EXP Multiplier (+50% TOTAL EXP GAIN) & +12% All Damage!',
        stats: { expMultiplier: 10, damageBonus: 1 }
      },

      // --- Left Branch: Vitality & Defense ---
      uni_exp_branch_left: {
        id: 'uni_exp_branch_left',
        name: 'Essence Shielding (เกราะคุ้มวิญญาณ)',
        type: 'minor',
        classType: 'universal',
        icon: '🛡️',
        cost: 70,
        x: 380,
        y: 440,
        connections: ['uni_root', 'uni_left_notable'],
        description: '+5% Permanent EXP Multiplier & +15 Max HP.',
        stats: { expMultiplier: 5, maxHp: 15 }
      },
      uni_left_notable: {
        id: 'uni_left_notable',
        name: 'Aegis of the Ancestors (ปราการบรรพบุรุษ)',
        type: 'notable',
        classType: 'universal',
        icon: '🏰',
        cost: 160,
        x: 280,
        y: 370,
        connections: ['uni_exp_branch_left'],
        description: 'NOTABLE: +5% Permanent EXP Multiplier & +3 Defense Armor.',
        stats: { expMultiplier: 5, defense: 3 }
      },

      // --- Right Branch: Velocity & Magnet ---
      uni_exp_branch_right: {
        id: 'uni_exp_branch_right',
        name: 'Swift Attunement (ก้าวย่างว่องไว)',
        type: 'minor',
        classType: 'universal',
        icon: '💨',
        cost: 70,
        x: 620,
        y: 440,
        connections: ['uni_root', 'uni_right_notable'],
        description: '+5% Permanent EXP Multiplier & +6% Move Speed.',
        stats: { expMultiplier: 5, moveSpeed: 1 }
      },
      uni_right_notable: {
        id: 'uni_right_notable',
        name: 'Celestial Vacuum (แรงดึงดูดดวงดาว)',
        type: 'notable',
        classType: 'universal',
        icon: '🧲',
        cost: 160,
        x: 720,
        y: 370,
        connections: ['uni_exp_branch_right'],
        description: 'NOTABLE: +5% Permanent EXP Multiplier & +25% Item Pickup Radius.',
        stats: { expMultiplier: 5, pickupRadius: 1 }
      }
    }
  }
};
